/**
 * Supplement interaction dataset, powers the programmatic /interactions/[pair]
 * pages and grounds the audit engine. Each entry is a real, well-documented
 * pairwise relationship using ids that exist in SUPPLEMENT_DB.
 *
 * Honest by design: we only publish a page for a pair we have something real to
 * say about (no thin "no known interaction" filler).
 */

export type InteractionKind = "synergy" | "timing" | "caution" | "redundant";

export interface Interaction {
  a: string;            // supplement id
  b: string;            // supplement id
  kind: InteractionKind;
  summary: string;      // one-line verdict
  detail: string;       // why it happens (1-2 sentences, plain English)
  advice: string;       // what to do
  evidence: "strong" | "moderate" | "emerging";
}

export const KIND_META: Record<InteractionKind, { label: string; verdict: string; hue: string; bg: string }> = {
  synergy:   { label: "Works better together", verdict: "Take together", hue: "#3f7a52", bg: "#f0f9f3" },
  timing:    { label: "Separate the timing",   verdict: "Space them apart", hue: "#b5751e", bg: "#fffbeb" },
  caution:   { label: "Use with caution",      verdict: "Check with a clinician", hue: "#b91c1c", bg: "#fef2f2" },
  redundant: { label: "Redundant together",    verdict: "Pick one", hue: "#6b4fc7", bg: "#f4f1ff" },
};

export const INTERACTIONS: Interaction[] = [
  { a: "iron", b: "calcium", kind: "timing", evidence: "strong",
    summary: "Calcium blocks iron absorption by up to ~50%.",
    detail: "Calcium competes with non-heme iron for the same DMT1 uptake transporter in the gut, so dairy or a calcium supplement in the same sitting can cut iron absorption by roughly a third to a half. The effect is largest for supplemental and plant iron and smaller for heme iron from meat.",
    advice: "Take iron on an empty stomach with about 200 mg of vitamin C, and keep calcium-rich meals or calcium pills at least 2 hours away. If iron upsets your stomach, a gentle form like bisglycinate with a small low-calcium snack is a reasonable compromise." },
  { a: "iron", b: "vit-c", kind: "synergy", evidence: "strong",
    summary: "Vitamin C dramatically boosts iron absorption.",
    detail: "Vitamin C reduces dietary iron to its more soluble ferrous form and shields it from inhibitors like tannins and phytates, which can lift uptake of non-heme iron several-fold. The benefit is greatest for plant and supplemental iron, exactly the iron most people struggle to absorb.",
    advice: "Take them together: pair your iron with roughly 200 mg of vitamin C or a vitamin-C-rich food such as citrus, peppers, or strawberries. There is no need for a separate megadose; a modest amount alongside the iron does the job." },
  { a: "iron", b: "zinc", kind: "timing", evidence: "moderate",
    summary: "High-dose iron and zinc compete for absorption.",
    detail: "Taken together in large supplemental doses, iron and zinc share absorption pathways in the gut and can each reduce the other's uptake. At the modest amounts found in food or a multivitamin this competition is minor.",
    advice: "If you supplement therapeutic doses of both, separate them by a couple of hours, for example iron in the morning on an empty stomach with vitamin C, and zinc with dinner to avoid nausea. Keep zinc under about 40 mg a day long-term." },
  { a: "calcium", b: "mag-glycinate", kind: "timing", evidence: "moderate",
    summary: "Large calcium and magnesium doses can compete.",
    detail: "At high doses, calcium and magnesium use some of the same transport in the gut, so taking large amounts of both at the same moment is a little less efficient. Around the ratios found in most supplements and foods this is rarely a real issue.",
    advice: "Modest doses together are fine. If you take large therapeutic amounts, split them across the day, and take magnesium in the evening, where it doubles as sleep and muscle-relaxation support. Favour food sources of calcium where you can." },
  { a: "coq10", b: "ubiquinol", kind: "redundant", evidence: "strong",
    summary: "CoQ10 and ubiquinol are the same nutrient.",
    detail: "Ubiquinol is simply the reduced, active form of CoQ10 (ubiquinone), and your body interconverts the two, so taking both means paying twice for the same nutrient with no added benefit for most people.",
    advice: "Pick one. Ubiquinol is worth the higher price if you are over about 40 or absorb poorly; standard CoQ10 is perfectly effective and cheaper for younger people. Take either with a fat-containing meal, since absorption is much better with food." },
  { a: "omega3", b: "omega3-algae", kind: "redundant", evidence: "strong",
    summary: "Two omega-3 sources doing the same job.",
    detail: "Fish oil and algae oil both deliver the same active omega-3 fats, EPA and DHA (algae is in fact the original source fish get theirs from), so taking both just overlaps and adds cost without extra benefit for most people.",
    advice: "Choose one: fish oil is cheaper and usually higher in EPA, while algae oil is the vegan, fish-free option and is gentler on burping. Compare on the EPA/DHA dose, not the capsule count." },
  { a: "5-htp", b: "tryptophan", kind: "caution", evidence: "moderate",
    summary: "Both raise serotonin, combining is rarely needed.",
    detail: "5-HTP and L-tryptophan feed the same serotonin pathway at different steps (tryptophan converts to 5-HTP, which converts to serotonin), so taking both pushes serotonin from two directions. Combined with an SSRI, SNRI, MAOI, or other serotonergic drug, this raises the risk of serotonin excess.",
    advice: "Use one, not both, and keep the dose modest. If you take any antidepressant or a migraine medication that affects serotonin, do not add either without talking to your doctor first, given the risk of serotonin syndrome." },
  { a: "nmn", b: "tmg", kind: "synergy", evidence: "emerging",
    summary: "TMG replaces methyl groups NMN uses up.",
    detail: "When the body clears the extra NAD+ that NMN produces, it attaches and uses up methyl groups, and the theory is that heavy NMN use could draw down the body's methyl supply; TMG (betaine) is a methyl donor that replaces them, which may prevent a shortfall.",
    advice: "Many people pair NMN with around 1 g of TMG daily as low-risk insurance, though whether the methyl drain is clinically meaningful in humans is unproven. It is a sensible, well-tolerated combination, and B-vitamins like folate and B12 support the same methylation system." },
  { a: "nr", b: "tmg", kind: "synergy", evidence: "emerging",
    summary: "TMG supports methylation alongside NR.",
    detail: "Nicotinamide riboside (NR) raises NAD+ much like NMN, and clearing the excess can consume methyl groups, so the same logic applies: TMG (betaine) donates methyl groups to replenish what the NAD+ pathway uses, guarding against a possible methylation shortfall.",
    advice: "Pairing NR with around 1 g of TMG daily is a common, reasonable longevity choice, though the human evidence that the methyl drain matters is still thin. It is low-risk and well tolerated, and adequate folate and B12 support the same system." },
  { a: "ashwagandha", b: "rhodiola", kind: "timing", evidence: "moderate",
    summary: "One calming, one stimulating adaptogen.",
    detail: "These two adaptogens pull in opposite directions: ashwagandha is calming and lowers cortisol, which suits the evening, while rhodiola is stimulating and fights fatigue, which suits the morning. Taken at the same time they can partly work against each other.",
    advice: "Rather than taking them together, split them: rhodiola early in the day on an empty stomach for energy and focus, and ashwagandha in the evening with food for stress and sleep. Avoid late-day rhodiola, which can disrupt sleep." },
  { a: "mag-glycinate", b: "mag-citrate", kind: "redundant", evidence: "strong",
    summary: "Two magnesium forms, usually one is enough.",
    detail: "Both are magnesium, just bound to different carriers: glycinate is gentle and calming and favours sleep and stress, while citrate draws water into the gut and is more laxative. Stacking both mainly adds elemental magnesium and digestive effects rather than new benefit.",
    advice: "Pick the form for your goal: glycinate at night for sleep and stress, citrate for occasional constipation. If you ever take both, keep the combined elemental magnesium sensible to avoid loose stools." },
  { a: "mag-glycinate", b: "mag-threonate", kind: "redundant", evidence: "moderate",
    summary: "Overlapping magnesium forms.",
    detail: "Threonate is marketed for cognition because it may raise brain magnesium, while glycinate is favoured for sleep and stress, but both simply raise your total magnesium and rarely need to be combined.",
    advice: "Choose one based on your main goal to avoid overshooting your intake. If cognition is the priority, threonate; for sleep and calm, glycinate is the cheaper, well-absorbed choice." },
  { a: "omega3", b: "ginkgo", kind: "caution", evidence: "moderate",
    summary: "Both can thin the blood.",
    detail: "Both have mild anti-platelet activity: omega-3 fats subtly reduce platelet aggregation, and ginkgo can do the same through its terpenoids. Alone at normal doses this is rarely an issue, but combined, and especially alongside aspirin, warfarin, or other anticoagulants, the effects can add up and raise bleeding risk.",
    advice: "For most healthy people, normal doses together are fine. If you take blood thinners or antiplatelet drugs, have a bleeding disorder, or have surgery or a dental procedure coming up, clear it with your doctor first and consider pausing both beforehand." },
  { a: "omega3", b: "nattokinase", kind: "caution", evidence: "moderate",
    summary: "Compounded blood-thinning effect.",
    detail: "Nattokinase is a fibrinolytic enzyme that breaks down fibrin and can reduce clot formation, while omega-3 is mildly anti-platelet. Stacked, the two act on different parts of clotting and can meaningfully shift the balance toward bleeding, particularly at higher nattokinase doses.",
    advice: "Do not combine these without medical guidance if you take anticoagulant or antiplatelet medication, have a clotting disorder, or are approaching surgery. For others, keep doses modest and stop before any procedure that carries a bleeding risk." },
  { a: "berberine", b: "chromium", kind: "synergy", evidence: "moderate",
    summary: "Both support healthy blood sugar.",
    detail: "Berberine improves insulin signalling and lowers blood glucose, with effects some trials compare to early diabetes medication, while chromium helps insulin move glucose into cells, so the two support healthy blood sugar through complementary mechanisms.",
    advice: "Reasonable to pair for metabolic support, but monitor closely if you take diabetes medication, since the combination can push blood sugar too low. Berberine also changes how the body processes many drugs, so check with a pharmacist or doctor before combining." },
  { a: "mag-glycinate", b: "d3k2", kind: "synergy", evidence: "moderate",
    summary: "Magnesium helps your body use vitamin D.",
    detail: "The enzymes that transport and activate vitamin D into its usable form all depend on magnesium, so if you are low in magnesium, supplemental D3 works less well, which is why the two are considered foundational partners (with K2 directing the resulting calcium to bone).",
    advice: "A good foundational pairing. Take D3 and K2 with a meal containing fat for absorption, ideally earlier in the day, and magnesium glycinate in the evening, where it also supports sleep and muscle relaxation." },
  { a: "curcumin", b: "omega3", kind: "synergy", evidence: "moderate",
    summary: "Complementary anti-inflammatory effects.",
    detail: "Curcumin and omega-3 fats calm inflammation through different routes, curcumin by quietening the NF-kB signalling that switches inflammatory genes on, and omega-3s by giving rise to specialised resolving mediators, so their effects can add up for joints and recovery.",
    advice: "A safe, common combination for joint comfort and post-exercise recovery. Choose a curcumin with an absorption enhancer such as piperine or a phospholipid form, take both with a fatty meal, and be cautious if you are on blood thinners, since both can mildly affect clotting." },
  { a: "green-tea", b: "iron", kind: "timing", evidence: "moderate",
    summary: "Green tea tannins inhibit iron absorption.",
    detail: "The polyphenols (tannins) in green tea bind non-heme iron in the gut and form complexes you cannot absorb, which can noticeably cut how much iron you take up from a supplement or a plant-based meal eaten at the same time.",
    advice: "Keep green tea (and other tea or coffee) at least 1 to 2 hours away from iron. Take iron with vitamin C instead, which counteracts these inhibitors. If you drink a lot of tea and are prone to low iron, watch the timing closely." },
  { a: "l-theanine", b: "green-tea", kind: "synergy", evidence: "moderate",
    summary: "Calm, focused energy together.",
    detail: "Green tea naturally contains both caffeine and L-theanine; adding extra L-theanine raises that ratio so the amino acid smooths the stimulation, giving alert, calm focus with fewer jitters and less of a crash.",
    advice: "A classic calm-focus pairing, fine to take together in the morning or early afternoon. A common ratio is roughly 2:1 theanine to caffeine; keep it earlier in the day to protect sleep." },
  { a: "zinc", b: "vit-c", kind: "synergy", evidence: "moderate",
    summary: "Immune-support pairing.",
    detail: "Zinc and vitamin C support different parts of the immune system, zinc by helping immune cells develop and hampering viral replication, vitamin C by supporting barrier and white-cell function, which is why they are bundled in so many cold-and-immune formulas.",
    advice: "Safe and sensible to take together, especially at the first sign of a cold. Take zinc with food to avoid nausea, keep it under about 40 mg a day and short-term, and do not expect either to prevent colds outright, since the effect is modest." },
  { a: "ashwagandha", b: "melatonin", kind: "synergy", evidence: "moderate",
    summary: "Both support sleep, different ways.",
    detail: "The two help sleep in different ways: ashwagandha lowers cortisol and the stress that keeps you wired, building its effect over weeks, while melatonin is a timing signal that tells your body it is night and shortens how long it takes to fall asleep.",
    advice: "A reasonable evening pairing for stress-related poor sleep. Start melatonin low, around 0.5 to 1 mg, since more is not better and can leave you groggy, and take ashwagandha daily with food. See a clinician for ongoing insomnia." },
  { a: "selenium", b: "iodine", kind: "synergy", evidence: "moderate",
    summary: "Thyroid pairing, but balance matters.",
    detail: "Both are essential for the thyroid: iodine is the raw material in thyroid hormone, while selenium runs the enzymes that convert and activate that hormone and protect the gland from the oxidative stress that iodine processing generates, so they genuinely work as a pair.",
    advice: "Useful together for thyroid support, but balance matters: do not mega-dose iodine, which can paradoxically trigger thyroid problems, and get selenium largely from food (a couple of Brazil nuts is plenty). Check with a clinician first if you have any thyroid disease." },

  // ── Mineral timing / competition ─────────────────────────────────────────
  { a: "iron", b: "mag-glycinate", kind: "timing", evidence: "moderate", summary: "Iron and magnesium can compete for absorption.", detail: "Both are positively charged minerals that share some of the same gut transport, so large supplemental doses taken together can modestly reduce how much of each you absorb. At the smaller amounts in food or a multivitamin this barely matters.", advice: "If you take therapeutic doses of both, separate them: iron in the morning on an empty stomach with vitamin C, and magnesium in the evening, where it also helps sleep. Pairing iron with vitamin C matters far more than avoiding magnesium." },
  { a: "calcium", b: "zinc", kind: "timing", evidence: "moderate", summary: "Calcium blunts zinc absorption.", detail: "High-dose calcium competes with zinc for absorption in the gut, so taking a large calcium supplement at the same time as zinc can lower how much zinc you take up, an effect seen mainly with supplements rather than normal food amounts.", advice: "If you take large doses of both, separate them by about 2 hours, for example calcium with one meal and zinc with another. Take zinc with food to avoid nausea, and do not exceed about 40 mg of zinc a day long-term." },
  { a: "iron", b: "psyllium", kind: "timing", evidence: "moderate", summary: "Fibre can bind iron.", detail: "Psyllium and other soluble fibres form a gel that can trap minerals like iron and slow their absorption as they pass through the gut, so taking them together blunts how much iron you get from a dose.", advice: "Keep iron and psyllium (and other fibre supplements) a couple of hours apart. Take iron on an empty stomach with vitamin C for best absorption, and use psyllium with plenty of water at a different time of day." },
  { a: "zinc", b: "mag-glycinate", kind: "timing", evidence: "emerging", summary: "Best taken a little apart at high doses.", detail: "Zinc and magnesium can compete a little for absorption when taken together in large amounts, which is why some advice spaces them, though the popular ZMA formula deliberately combines them at balanced doses and is widely used without problems.", advice: "Balanced doses together (as in ZMA) are fine and convenient in the evening. If you take large therapeutic doses of each, space them out, take zinc with food to avoid nausea, and keep zinc under about 40 mg a day long-term." },

  // ── B-vitamin / methylation synergies ────────────────────────────────────
  { a: "methylfolate", b: "b12", kind: "synergy", evidence: "strong", summary: "Folate and B12 work as a pair.", detail: "Folate and B12 work as a pair in methylation and red-blood-cell formation, each recycling the other. Crucially, supplementing folate alone can correct the anemia of a B12 deficiency while the nerve damage quietly progresses, which is why they are tested and taken together.", advice: "Take them together, easiest as a methylated B-complex. If you are vegan, over 50, or on metformin, prioritise B12 and have levels checked rather than relying on folate alone." },
  { a: "vit-b6", b: "methylfolate", kind: "synergy", evidence: "strong", summary: "Team players for homocysteine.", detail: "Vitamin B6, folate, and B12 each handle a different step in clearing homocysteine, an amino acid that, when elevated, is linked to cardiovascular and cognitive risk, so together they lower it more reliably than any one alone.", advice: "Combine them, most simply as a methylated B-complex that supplies B6, methylfolate, and methyl-B12 together. If your homocysteine has tested high, recheck after a few months, and prioritise B12 status if you are vegan, older, or on metformin." },
  { a: "vit-b6", b: "b12", kind: "synergy", evidence: "moderate", summary: "Nerve and energy support together.", detail: "Both B6 and B12 are central to healthy nerve function and to turning food into usable energy, and they are partners (with folate) in the homocysteine and methylation pathways, so they are naturally taken together.", advice: "Fine together, and a B-complex is the simplest way to cover both. If you have unexplained tingling, numbness, or fatigue, ask for a B12 test specifically, since deficiency is common in vegans, older adults, and long-term metformin or acid-blocker users." },
  { a: "tmg", b: "b-complex", kind: "synergy", evidence: "moderate", summary: "Both support methylation.", detail: "TMG (betaine) donates a methyl group to recycle homocysteine back into methionine, and the B-vitamins (especially folate, B6, and B12) run the parallel methylation route, so together they give the body two ways to keep homocysteine in check.", advice: "A reasonable combination for methylation and homocysteine support. A typical TMG dose is around 1 to 3 g daily alongside a B-complex. If you are using it for a raised homocysteine reading, recheck the level after a few months to confirm it is working." },
  { a: "5-htp", b: "vit-b6", kind: "synergy", evidence: "moderate", summary: "B6 helps convert 5-HTP to serotonin.", detail: "The enzyme that turns 5-HTP into serotonin depends on vitamin B6 as a cofactor, so adequate B6 supports that conversion, which is why many 5-HTP products already include a little B6.", advice: "Taking B6 alongside 5-HTP is sensible. Crucially, do not combine 5-HTP with antidepressants (SSRIs, SNRIs, MAOIs) or other serotonergic drugs without medical advice, because of the risk of serotonin syndrome, and keep 5-HTP to short-term use." },
  { a: "tryptophan", b: "vit-b6", kind: "synergy", evidence: "moderate", summary: "B6 aids tryptophan metabolism.", detail: "Vitamin B6 is a cofactor along the pathway that converts tryptophan toward serotonin and niacin, so having enough B6 supports that conversion when you supplement tryptophan for mood or sleep.", advice: "Pairing the two is reasonable, but avoid stacking tryptophan with other serotonin boosters such as 5-HTP or SSRIs without a doctor's guidance, given the serotonin-syndrome risk. Tryptophan is usually taken in the evening for sleep." },
  { a: "iron", b: "b12", kind: "synergy", evidence: "moderate", summary: "Both build healthy red blood cells.", detail: "Iron and B12 fix different causes of anaemia and fatigue: iron shortage causes small, pale red cells, while B12 (or folate) shortage causes large, immature ones, so checking and correcting both covers the common nutritional anaemias.", advice: "Fine to take together, but take iron away from calcium, tea, and coffee, which block its absorption, and pair it with vitamin C instead. Get the cause of any anaemia diagnosed rather than guessing, since the treatment depends on which deficiency you have." },
  { a: "multivit", b: "b-complex", kind: "redundant", evidence: "moderate", summary: "Overlapping B vitamins.", detail: "A multivitamin already contains the full set of B vitamins, so adding a separate B-complex on top mostly doubles up. Since B vitamins are water-soluble, the excess is largely excreted rather than stored.", advice: "Use one. Add a B-complex only if you specifically need higher B doses, for example methylfolate and B12 for a raised homocysteine, or extra support on a vegan diet. Otherwise the multivitamin alone is enough and the second product is wasted money." },
  { a: "multivit", b: "biotin", kind: "redundant", evidence: "moderate", summary: "Your multivitamin likely has biotin.", detail: "Most multivitamins already include biotin, often well above the tiny amount you actually need, so a separate high-dose biotin is redundant for the average person, and true biotin deficiency is rare.", advice: "Add standalone biotin only for a specific, time-limited hair or nail goal, and know the evidence is weak unless you are deficient. Important: high-dose biotin can skew thyroid and heart (troponin) blood tests, so tell your doctor before any lab work." },

  // ── Mitochondrial / energy synergies ─────────────────────────────────────
  { a: "coq10", b: "pqq", kind: "synergy", evidence: "moderate", summary: "Mitochondrial duo.", detail: "CoQ10 keeps your existing mitochondria producing energy and acts as an antioxidant inside them, while PQQ is thought to encourage the creation of new mitochondria, so the pair supports both the function and the number of your cells' power plants.", advice: "A common, well-tolerated pairing for energy and healthy aging. Both are fat-soluble, so take them with a meal that contains fat, and give it several weeks. Ubiquinol is the better-absorbed CoQ10 form for people over about 40." },
  { a: "ala", b: "acetyl-l-carnitine", kind: "synergy", evidence: "moderate", summary: "Classic mitochondrial pairing.", detail: "Acetyl-L-carnitine (ALCAR) shuttles fatty acids into mitochondria to be burned for energy and supports the brain, while alpha-lipoic acid is a mitochondrial antioxidant that also helps regenerate other antioxidants, so the two are studied together for energy and cognition.", advice: "A reasonable combination, often taken in the morning for an energy and focus angle. Take ALA on an empty stomach for absorption and watch blood sugar if you are diabetic, since ALA can lower it. Both are generally well tolerated." },
  { a: "acetyl-l-carnitine", b: "l-carnitine", kind: "redundant", evidence: "strong", summary: "Two forms of carnitine.", detail: "ALCAR is simply acetylated L-carnitine, so both raise your carnitine levels; the difference is that ALCAR crosses into the brain more readily, while plain L-carnitine is geared toward muscle and exercise.", advice: "Pick one for your goal: ALCAR for cognition and focus, L-carnitine for general energy and exercise. Taking both mostly duplicates the carnitine pool and adds little beyond a single adequate dose." },
  { a: "coq10", b: "omega3", kind: "synergy", evidence: "moderate", summary: "Heart-health pairing.", detail: "CoQ10 fuels energy production in hard-working heart muscle and acts as an antioxidant, while omega-3 fats support a healthy heart rhythm and lower triglycerides, so together they cover complementary parts of cardiovascular health.", advice: "A common and sensible heart-support combination. Both absorb far better with a fatty meal, so take them together with food. If you are on a statin, which can lower CoQ10, or any heart medication, mention these to your doctor." },
  { a: "ubiquinol", b: "pqq", kind: "synergy", evidence: "moderate", summary: "Mitochondrial support.", detail: "This is the same mitochondrial logic as CoQ10 plus PQQ, but with ubiquinol, the reduced and better-absorbed form of CoQ10: ubiquinol supports energy output in existing mitochondria while PQQ is thought to promote new ones.", advice: "A fine pairing, and ubiquinol is the form worth paying for if you are over about 40 or absorb CoQ10 poorly. Take both with a fat-containing meal, and give it several weeks to notice any change in energy." },

  // ── Antioxidant recycling ────────────────────────────────────────────────
  { a: "vit-c", b: "vit-e", kind: "synergy", evidence: "moderate", summary: "They regenerate each other.", detail: "Vitamin C is water-soluble and vitamin E is fat-soluble, so they protect different compartments of the cell, and vitamin C regenerates oxidised vitamin E back to its active form so it can keep working, a genuine recycling partnership.", advice: "A natural antioxidant pairing found together in many foods. Get most of both from a varied diet of fruit, vegetables, nuts, and seeds; if you supplement vitamin E, avoid high doses, which can act as a pro-oxidant and may thin the blood." },
  { a: "nac", b: "glycine", kind: "synergy", evidence: "emerging", summary: "GlyNAC, raises glutathione.", detail: "Glutathione, the body's master antioxidant, is built from three amino acids, and the two most often in short supply with age are cysteine (supplied by NAC) and glycine, so providing both (GlyNAC) raises glutathione more than either alone.", advice: "A promising combination for antioxidant defence and healthy aging, studied at gram-level doses of each. Introduce it gradually, take NAC away from any nitrate heart medication, and check with a clinician first if you have a health condition or take regular medication." },
  { a: "nac", b: "glutathione", kind: "synergy", evidence: "moderate", summary: "Precursor plus the finished product.", detail: "NAC supplies cysteine, the rate-limiting raw material your cells use to make glutathione, while a glutathione supplement provides the finished antioxidant directly, so taking both supports glutathione status from two directions.", advice: "Fine together, though NAC alone is often enough and far cheaper, since oral glutathione is broken down and absorbed inconsistently (liposomal forms aim to improve this). Take NAC away from nitrate heart medication, and do not rely on either in place of medical care." },
  { a: "ala", b: "glutathione", kind: "synergy", evidence: "moderate", summary: "ALA helps recycle glutathione.", detail: "Alpha-lipoic acid is an unusual antioxidant that works in both water and fat and helps regenerate other antioxidants, including glutathione, vitamin C, and vitamin E, so it supports the whole antioxidant network rather than acting alone.", advice: "A complementary antioxidant pairing. Take ALA on an empty stomach for better absorption, and if you are diabetic monitor your blood sugar, since ALA can lower it and may add to glucose-lowering medication." },
  { a: "vit-c", b: "glutathione", kind: "synergy", evidence: "moderate", summary: "Vitamin C spares glutathione.", detail: "Vitamin C and glutathione back each other up: vitamin C helps keep glutathione in its active, reduced form, and glutathione in turn helps regenerate vitamin C, so each spares the other and extends its antioxidant life.", advice: "A reasonable antioxidant combination, though a diet rich in fruit and vegetables plus adequate vitamin C does much of this naturally. If you supplement, modest doses are fine; mega-dosing vitamin C mostly leads to it being excreted." },
  { a: "vit-e", b: "selenium", kind: "synergy", evidence: "moderate", summary: "Antioxidant teammates.", detail: "Selenium is the core of glutathione-peroxidase enzymes that neutralise peroxides inside the cell, while vitamin E protects the fats in cell membranes from the same oxidative damage, so the two guard different fronts of the same battle.", advice: "Fine together at sensible doses. Selenium has a relatively narrow safe range, so do not megadose it (a couple of Brazil nuts supply a day's worth), and keep vitamin E modest, since high doses offer no benefit and may thin the blood." },
  { a: "omega3", b: "astaxanthin", kind: "synergy", evidence: "moderate", summary: "Astaxanthin protects omega-3s.", detail: "Omega-3 fats are polyunsaturated and prone to oxidising (going rancid), and astaxanthin is a powerful fat-soluble antioxidant that helps prevent that both in the capsule and once the fats are in your body, so it protects the very thing you are taking.", advice: "A good pairing, and some fish-oil products already include astaxanthin for this reason. Take both with a fatty meal for absorption, and choose a fresh, third-party-tested fish oil, since a rancid oil undoes much of the benefit." },
  { a: "omega3", b: "vit-e", kind: "synergy", evidence: "emerging", summary: "Vitamin E guards omega-3s.", detail: "A small amount of vitamin E helps keep polyunsaturated omega-3 fats from oxidising and turning rancid, which is why many fish-oil capsules already contain a little as a built-in preservative.", advice: "Fine to pair, but you rarely need a separate high-dose vitamin E for this, since the trace in a quality fish oil is usually enough. If you do supplement vitamin E, keep the dose modest, as large amounts can act as a pro-oxidant and mildly thin the blood." },

  // ── Sleep / calm synergies ───────────────────────────────────────────────
  { a: "glycine", b: "mag-glycinate", kind: "synergy", evidence: "moderate", summary: "Calming sleep pairing.", detail: "Glycine is a calming neurotransmitter that gently lowers core body temperature to help you drop off, while magnesium quiets an over-active nervous system and relaxes muscle, so the two support sleep onset and depth through different routes.", advice: "A gentle, well-tolerated evening combination. Take roughly 3 g of glycine with 200 to 400 mg of magnesium glycinate (which itself supplies extra glycine) about 30 to 60 minutes before bed, and keep the magnesium modest if you are prone to loose stools." },
  { a: "l-theanine", b: "mag-glycinate", kind: "synergy", evidence: "moderate", summary: "Relaxation without sedation.", detail: "L-theanine raises calming alpha brain-wave activity and takes the edge off stress without making you drowsy, while magnesium relaxes muscle and dampens an over-active nervous system, so together they wind you down without knocking you out.", advice: "A good calm pairing for day or evening. A typical dose is 100 to 200 mg of L-theanine with 200 to 400 mg of magnesium glycinate; use the theanine earlier for calm focus and the magnesium at night for sleep." },
  { a: "gaba", b: "l-theanine", kind: "synergy", evidence: "emerging", summary: "Calm-focus pairing.", detail: "L-theanine promotes relaxed alertness, and GABA is the brain's main inhibitory (calming) neurotransmitter, so the pair is used to ease tension and help sleep onset. How much oral GABA actually reaches the brain is debated, which keeps the evidence emerging.", advice: "Low-risk to try in the evening or during stress. Effects are gentle rather than sedating; start with around 100 to 200 mg of each, and do not lean on it instead of addressing what is driving the stress." },
  { a: "melatonin", b: "mag-glycinate", kind: "synergy", evidence: "moderate", summary: "Sleep onset plus relaxation.", detail: "Melatonin is a timing signal that tells your body it is night and shortens how long it takes to fall asleep, while magnesium relaxes muscle and the nervous system, so one cues sleep and the other helps your body settle into it.", advice: "A sensible evening pair taken 30 to 60 minutes before bed. Start melatonin low, around 0.5 to 1 mg, since more is not better and can leave you groggy, alongside about 200 to 400 mg of magnesium glycinate." },
  { a: "valerian", b: "gaba", kind: "synergy", evidence: "emerging", summary: "Sedative pairing.", detail: "Valerian appears to work partly by raising GABA activity, the brain's main calming signal, and GABA supplements target the same system, so the two are combined in sleep formulas for an additive wind-down effect.", advice: "Use in the evening only and start low, as the combination can leave some people groggy the next morning. Avoid stacking it with alcohol, sedatives, or sleep medication, and do not drive after taking it until you know how it affects you." },
  { a: "valerian", b: "passionflower", kind: "synergy", evidence: "moderate", summary: "Traditional sleep blend.", detail: "Both are calming herbs thought to act on GABA pathways, and they appear together in many traditional sleep and anxiety formulas, where their mild sedative effects are meant to add up.", advice: "A reasonable evening blend for occasional restlessness. Take it before bed, avoid combining it with alcohol or sedative medication, and treat it as short-term support rather than an indefinite nightly habit without checking with a clinician." },
  { a: "valerian", b: "lemon-balm", kind: "synergy", evidence: "moderate", summary: "Calming herbal pairing.", detail: "Lemon balm is a gentle calming herb and valerian is a stronger sedative one, and the two are traditionally paired (and studied together) for relaxation and easier sleep onset.", advice: "Take this combination before bed for occasional sleeplessness or nervous tension. It is generally gentle, but avoid mixing it with alcohol or sedatives, and skip it before driving since valerian can cause drowsiness." },
  { a: "magnolia-bark", b: "gaba", kind: "synergy", evidence: "emerging", summary: "Stress-and-sleep pairing.", detail: "Magnolia bark's honokiol and magnolol compounds lower cortisol and enhance GABA signalling, and adding GABA targets the same calming system, so the pair is used for stress that keeps you awake at night.", advice: "Best in the evening when racing thoughts or stress disrupt sleep. Start with modest doses, avoid combining it with sedatives or alcohol, and see a clinician if anxiety or insomnia is persistent rather than occasional." },
  { a: "ashwagandha", b: "l-theanine", kind: "synergy", evidence: "moderate", summary: "Daytime stress pairing.", detail: "Ashwagandha lowers cortisol and blunts the stress response over weeks of daily use, while L-theanine smooths anxious, jittery focus within an hour, so you get both an immediate calm and a longer-term lowering of baseline stress.", advice: "Works morning or evening. Ashwagandha (typically 300 to 600 mg of a standardised extract) needs consistent daily use to build its effect, whereas theanine (100 to 200 mg) acts acutely. Take ashwagandha with food, and check with a doctor if you have thyroid disease." },
  { a: "ashwagandha", b: "magnolia-bark", kind: "synergy", evidence: "emerging", summary: "Cortisol-lowering pair.", detail: "Both target the stress and cortisol axis: ashwagandha dampens the HPA stress response, and magnolia bark lowers cortisol while boosting calming GABA tone, so together they aim at stress-driven tension and poor sleep.", advice: "A good evening stress-support pair for people whose stress peaks at night. Use it consistently, keep doses modest, and avoid combining it with sedatives. See a clinician for ongoing anxiety, and note ashwagandha is best avoided in pregnancy." },

  // ── Serotonin / dopamine cautions ────────────────────────────────────────
  { a: "5-htp", b: "saffron", kind: "caution", evidence: "moderate", summary: "Both raise serotonin.", detail: "Both lift mood by increasing serotonin activity, 5-HTP as a direct serotonin precursor and saffron through serotonergic compounds. Stacking two serotonergic supplements makes the combined effect hard to dose and riskier alongside antidepressants.", advice: "Choose one rather than both. If you take an SSRI, SNRI, or other serotonergic medication, speak with your clinician before using either, as the combination can contribute to serotonin excess." },
  { a: "5-htp", b: "mucuna", kind: "caution", evidence: "emerging", summary: "Serotonin + dopamine push.", detail: "5-HTP raises serotonin while mucuna (a natural L-dopa source) raises dopamine, so combining them pushes two major neurotransmitters at once. The interaction is poorly studied, can feel intense, and is risky alongside mood or Parkinson's medication.", advice: "Approach this combination cautiously and only short-term, if at all. Avoid it entirely if you take antidepressants, MAOIs, or dopaminergic drugs, and check with your doctor first." },
  { a: "mucuna", b: "l-tyrosine", kind: "redundant", evidence: "moderate", summary: "Two dopamine precursors.", detail: "Both raise dopamine through overlapping pathways: mucuna is a natural source of L-dopa, the direct precursor to dopamine, while L-tyrosine is an earlier building block the body converts toward dopamine, so stacking them pushes the same system twice.", advice: "Use one rather than both to avoid overshooting. Mucuna is the stronger, more direct option but should be approached cautiously and not combined with Parkinson's or antidepressant medication without medical advice; L-tyrosine is the gentler daytime focus choice." },

  // ── Nootropic synergies ──────────────────────────────────────────────────
  { a: "alpha-gpc", b: "citicoline", kind: "redundant", evidence: "moderate", summary: "Two choline donors.", detail: "Both are choline donors that raise acetylcholine for focus and memory; citicoline also supplies uridine, while alpha-GPC delivers a higher percentage of choline by weight. Their core effect overlaps.", advice: "Pick one: citicoline for the added uridine and a smoother feel, alpha-GPC for a higher choline yield. Stacking both rarely adds noticeable benefit and mainly raises the cost and the chance of a headache, the usual sign you have pushed choline too high." },
  { a: "huperzine", b: "alpha-gpc", kind: "synergy", evidence: "emerging", summary: "Raise and preserve acetylcholine.", detail: "Alpha-GPC supplies the choline your brain turns into acetylcholine, the focus-and-memory neurotransmitter, while huperzine A slows the enzyme that breaks acetylcholine down, so one raises the supply and the other protects it.", advice: "A potent short-term focus pairing, but cycle huperzine rather than taking it daily, since its long half-life lets it build up and cause headaches, nausea, or vivid dreams. Avoid it alongside cholinergic medication, and start with low doses." },
  { a: "citicoline", b: "phosphatidylserine", kind: "synergy", evidence: "moderate", summary: "Membrane and acetylcholine support.", detail: "Citicoline raises acetylcholine for focus and also feeds phosphatidylcholine into brain-cell membranes, while phosphatidylserine is a structural membrane fat tied to memory and a calmer stress response, so the two support cognition from complementary angles.", advice: "A reasonable nootropic pairing for memory and mental clarity, especially with age-related forgetfulness. Both are well tolerated; typical doses are around 250 mg of citicoline and 100 mg of phosphatidylserine, and both need a few weeks of consistent use to judge." },
  { a: "bacopa", b: "lions-mane", kind: "synergy", evidence: "emerging", summary: "Memory plus nerve growth.", detail: "Bacopa improves how well you retain and recall information, with most trials showing a benefit only after 8 to 12 weeks, while lion's mane is studied for nerve-growth-factor support, so the pair works on memory from two slow-building directions.", advice: "Both need weeks of daily, consistent use, so judge the stack over a couple of months rather than a few days. Take bacopa with food to limit stomach upset, and choose a lion's mane that specifies its fruiting-body content." },
  { a: "lions-mane", b: "alpha-gpc", kind: "synergy", evidence: "emerging", summary: "Nootropic stack.", detail: "Alpha-GPC delivers choline that the brain converts into acetylcholine for sharper focus within hours, while lion's mane is studied for slower nerve-growth-factor support, so you get an acute focus lift on top of a longer-term cognitive angle.", advice: "A common focus stack: you may feel the alpha-GPC the same day, but give lion's mane several weeks of daily use to judge. Keep alpha-GPC modest (around 300 mg) since too much choline can trigger headaches, and take both with food." },
  { a: "phosphatidylserine", b: "omega3", kind: "synergy", evidence: "moderate", summary: "Brain-membrane pairing.", detail: "Phosphatidylserine and the omega-3 DHA are both core structural fats in neuronal membranes, and a meaningful share of supplemental phosphatidylserine is bound to DHA, so they naturally complement each other for memory, mood, and stress resilience.", advice: "A sound combination for cognition and mood. Take them together with a meal that contains fat to aid absorption; common doses are around 100 mg of phosphatidylserine and a fish or algae oil supplying 500 mg or more of combined EPA and DHA." },
  { a: "choline", b: "omega3", kind: "synergy", evidence: "moderate", summary: "Brain-building pair.", detail: "Choline and the omega-3 DHA are both critical building blocks for brain-cell membranes and, in pregnancy, for fetal brain development, and they are frequently studied together for memory and neurodevelopment.", advice: "A genuinely complementary pair for brain health and especially relevant before and during pregnancy, though pregnant women should follow a clinician's dosing guidance. Take both with food, and note that eggs and oily fish supply meaningful amounts of each from diet alone." },
  { a: "l-tyrosine", b: "green-tea", kind: "synergy", evidence: "emerging", summary: "Focus under stress.", detail: "L-tyrosine is the raw material for dopamine and noradrenaline, which get depleted under stress and heavy mental load, while green tea pairs caffeine with calming L-theanine, so together they aim to sustain focus when you are stressed or tired.", advice: "A good daytime focus pairing before demanding or stressful tasks. Take it earlier in the day to protect sleep, mind your total caffeine across all sources, and skip the green-tea caffeine late in the day or if you are caffeine-sensitive." },
  { a: "bacopa", b: "ginkgo", kind: "synergy", evidence: "emerging", summary: "Memory plus circulation.", detail: "Bacopa supports memory consolidation and recall over weeks of use, while ginkgo is taken to improve blood flow to the brain, so the pair targets cognition through a memory mechanism and a circulatory one.", advice: "A reasonable memory stack, but give it 8 to 12 weeks to judge. Note that ginkgo has mild blood-thinning activity, so use caution and check with your doctor if you take anticoagulant or antiplatelet medication or have surgery coming up." },

  // ── Performance / muscle ─────────────────────────────────────────────────
  { a: "creatine", b: "beta-alanine", kind: "synergy", evidence: "strong", summary: "Strength plus endurance, different systems.", detail: "These target different systems: creatine restores the ATP-phosphocreatine energy pathway for short, powerful efforts, while beta-alanine raises muscle carnosine to buffer the acid that builds during sustained high-intensity work. That is why so many pre-workouts bundle them.", advice: "A staple performance pairing, safe to take daily. Both work by saturating muscle over weeks, so take them consistently rather than only on training days; beta-alanine's harmless skin tingling can be reduced by splitting the dose." },
  { a: "creatine", b: "hmb", kind: "synergy", evidence: "moderate", summary: "Build and protect muscle.", detail: "Creatine improves training performance and helps build strength and muscle, while HMB (a leucine metabolite) mainly slows muscle protein breakdown, so one helps you build and the other helps you hold onto muscle.", advice: "A useful pairing when muscle loss is a risk, such as in a calorie deficit, during injury layoffs, or for older adults. Take creatine consistently at 3 to 5 g daily and HMB at about 3 g; for most younger trainees, creatine alone does the heavy lifting." },
  { a: "creatine", b: "whey-isolate", kind: "synergy", evidence: "strong", summary: "Classic muscle-building combo.", detail: "These cover different bases: whey supplies the amino acids that are the raw material for muscle repair, while creatine improves training performance and cell hydration so you can train harder and recover. Together they are the most evidence-backed muscle-building pair.", advice: "A classic, safe daily combination. Take about 3 to 5 g creatine consistently (timing matters little) and enough protein to hit your daily target; post-workout is a convenient time for both." },
  { a: "l-citrulline", b: "beetroot", kind: "synergy", evidence: "moderate", summary: "Nitric-oxide 'pump' pairing.", detail: "Both raise nitric oxide to widen blood vessels and improve blood flow, but by different routes: citrulline converts to arginine to feed the enzyme that makes nitric oxide, while beetroot supplies dietary nitrates the body converts along a separate pathway.", advice: "A common pre-workout 'pump' and endurance stack. Take citrulline (around 6 to 8 g) and beetroot about 1 to 2 hours before training. Beetroot can turn urine or stool pink, which is harmless, and both may slightly lower blood pressure." },
  { a: "l-citrulline", b: "l-arginine", kind: "redundant", evidence: "strong", summary: "Citrulline raises arginine anyway.", detail: "L-citrulline converts to L-arginine in the kidneys and raises blood arginine more reliably than arginine taken directly, because oral arginine is largely broken down in the gut first. So pairing them adds little.", advice: "Use citrulline (around 6 to 8 g pre-workout); adding separate arginine on top gives little extra. Save the money and the pill count for a single effective dose." },
  { a: "beetroot", b: "l-arginine", kind: "synergy", evidence: "emerging", summary: "Blood-flow pairing.", detail: "Beetroot delivers dietary nitrates that the body converts to nitric oxide, while L-arginine is a direct precursor the nitric-oxide enzyme uses, so the two feed the same blood-flow pathway from two entry points.", advice: "Fine as a pre-workout pairing for blood flow, though L-citrulline is usually a better-value arginine source since oral arginine is largely broken down in the gut. Take them 1 to 2 hours before training, and expect a mild blood-pressure-lowering effect." },
  { a: "beta-alanine", b: "taurine", kind: "timing", evidence: "emerging", summary: "They compete for uptake.", detail: "Beta-alanine and taurine are taken up by the same transporter into muscle and nerve cells, so in theory very high doses of one could compete with the other, though in practice this rarely causes a noticeable problem at normal supplement amounts.", advice: "A minor concern for most people. If you take large doses of both, you can space them out, but it is rarely necessary. Beta-alanine's harmless skin tingling can be eased by splitting the dose, and both work by building up in muscle over weeks." },
  { a: "bcaa", b: "eaa", kind: "redundant", evidence: "strong", summary: "EAAs already contain BCAAs.", detail: "Essential amino acids (EAAs) already include the three branched-chain amino acids plus the rest of the essentials your body needs to actually build muscle protein. BCAAs alone provide only part of that set.", advice: "Choose EAAs, they are the more complete option for muscle protein synthesis. Separate BCAAs add cost without advantage if you already take EAAs or enough total protein." },
  { a: "whey-isolate", b: "bcaa", kind: "redundant", evidence: "strong", summary: "Whey is already rich in BCAAs.", detail: "A whey shake already delivers more BCAAs than a typical BCAA serving, plus all the other essential amino acids needed for muscle repair. Adding standalone BCAAs on top is largely redundant.", advice: "If you take whey, skip separate BCAAs and put the budget toward total daily protein. BCAAs are mainly useful when training fasted without any protein source nearby." },
  { a: "whey-isolate", b: "plant-protein", kind: "redundant", evidence: "moderate", summary: "Two protein sources.", detail: "Both supply the protein your muscles use to repair and grow; the differences are practical: whey is a complete dairy protein that is rapidly absorbed and very high in leucine, while plant blends are dairy-free and need good pairing (such as pea plus rice) to cover all amino acids.", advice: "Pick one based on your diet and digestion: plant protein if you are vegan or sensitive to dairy, whey if you tolerate it and want the most leucine per scoop. What matters most is hitting your total daily protein; the source is secondary." },
  { a: "creatine", b: "taurine", kind: "synergy", evidence: "emerging", summary: "Cell hydration plus performance.", detail: "Both draw water into muscle cells (cell volumising) and support exercise performance, and taurine has its own roles in muscle contraction and focus, so they are often bundled in pre-workouts, though the added benefit of taurine on top of creatine is still emerging.", advice: "Fine to take together and well tolerated. Take creatine consistently at 3 to 5 g daily (timing matters little); taurine is commonly 1 to 2 g. Stay well hydrated, which helps both do their job." },
  { a: "tart-cherry", b: "omega3", kind: "synergy", evidence: "moderate", summary: "Recovery pairing.", detail: "Both ease the inflammation and muscle soreness that follow hard training: tart cherry supplies anthocyanins that lower oxidative stress and may aid sleep, while omega-3 fats dampen the inflammatory response, so they support recovery through complementary routes.", advice: "A good post-training recovery pairing, especially around intense or unaccustomed exercise. Note that blunting inflammation routinely may slightly mute long-term muscle gains, so many lifters save these for competition or heavy phases rather than every day." },

  // ── Joint / skin / beauty ────────────────────────────────────────────────
  { a: "glucosamine", b: "msm", kind: "synergy", evidence: "moderate", summary: "Joint-support staple.", detail: "Glucosamine supplies a building block for cartilage and joint fluid, while MSM provides sulfur that supports connective tissue and appears to ease joint pain and stiffness, so the two are bundled in most joint formulas for structure plus comfort.", advice: "A staple combination for knee and joint comfort, typically dosed around 1500 mg of glucosamine and 1 to 3 g of MSM daily. Give it 4 to 8 weeks, and note glucosamine is often made from shellfish, so check the source if you have an allergy." },
  { a: "glucosamine", b: "boswellia", kind: "synergy", evidence: "moderate", summary: "Structure plus anti-inflammatory.", detail: "Glucosamine supports the cartilage matrix itself, while boswellia's boswellic acids calm the inflammatory enzymes that drive joint pain and stiffness, so one targets the joint's structure and the other the inflammation layered on top.", advice: "A reasonable joint stack for osteoarthritis-type discomfort, often taken as glucosamine around 1500 mg daily with a standardised boswellia extract. Give it several weeks, and check with your doctor if you take anti-inflammatory or blood-thinning medication." },
  { a: "boswellia", b: "curcumin", kind: "synergy", evidence: "moderate", summary: "Anti-inflammatory pair.", detail: "Boswellia and curcumin dampen joint inflammation through different enzymes (boswellia mainly via 5-LOX, curcumin via COX and NF-kB signalling), so combining them hits the inflammatory cascade at more than one point.", advice: "A common joint-and-recovery combination. Choose a curcumin with an absorption enhancer such as piperine or a phospholipid form, since plain curcumin is poorly absorbed, and check with a clinician if you take blood thinners, as both can mildly affect clotting." },
  { a: "curcumin", b: "ginger", kind: "synergy", evidence: "moderate", summary: "Anti-inflammatory roots.", detail: "Turmeric (curcumin) and ginger are related roots with complementary anti-inflammatory effects, and ginger adds digestive and anti-nausea benefits, so the pair is used for joint comfort, recovery, and gut ease.", advice: "A safe, food-derived combination. Pick a curcumin with an absorption enhancer like piperine or a phospholipid form, take both with a meal, and be cautious if you are on blood thinners or have gallstones, since both can stimulate bile flow." },
  { a: "collagen", b: "vit-c", kind: "synergy", evidence: "strong", summary: "Vitamin C is required to build collagen.", detail: "Vitamin C is a required cofactor for the enzymes that cross-link collagen, so without enough of it your body cannot build collagen properly no matter how much you supplement. Pairing them supports skin, joints, tendons, and bone.", advice: "Take collagen (typically 10 to 15 g) together with vitamin C, either as a supplement or a vitamin-C-rich food. Consistent daily use over 8 to 12 weeks is what tends to show results in skin and joint studies." },
  { a: "collagen", b: "hyaluronic-acid", kind: "synergy", evidence: "moderate", summary: "Skin-hydration pairing.", detail: "Collagen peptides supply the amino acids and signals that support the skin's structural framework, while hyaluronic acid is the molecule that holds water in skin, so one targets firmness and the other plumpness and hydration.", advice: "A popular skin-and-joint beauty combination. Take collagen (typically 10 to 15 g) with vitamin C to support collagen formation, give it 8 to 12 weeks of daily use, and remember that sun protection and not smoking do more for skin than any supplement." },
  { a: "collagen", b: "silica", kind: "synergy", evidence: "emerging", summary: "Skin, hair, and nails.", detail: "Collagen provides the protein scaffold for skin, hair, and nails, while silica (often from bamboo or horsetail) is involved in collagen formation and connective-tissue strength, so the pair is marketed together for beauty-from-within support.", advice: "A reasonable beauty pairing. Take collagen consistently (10 to 15 g daily) with vitamin C, and treat results as gradual over months. Evidence for added silica is still early, so set modest expectations and prioritise overall protein and hydration." },
  { a: "collagen", b: "biotin", kind: "synergy", evidence: "emerging", summary: "Hair and nail support.", detail: "Collagen supplies amino acids for the skin and nail matrix, while biotin is a B-vitamin used to build keratin, the protein in hair and nails, so the two are paired for hair, skin, and nail goals.", advice: "A common beauty combination, though most people already get enough biotin from food, so extra mainly helps if you are genuinely low. Important: high-dose biotin can distort thyroid and troponin blood tests, so tell your doctor you take it before any lab work." },
  { a: "lutein", b: "astaxanthin", kind: "synergy", evidence: "moderate", summary: "Eye-protection pairing.", detail: "Lutein concentrates in the macula where it filters damaging blue light, while astaxanthin is a potent antioxidant that also reaches eye tissue and may ease eye fatigue, so the two carotenoids protect vision through filtering and antioxidant routes.", advice: "A good pairing for screen-heavy lifestyles and long-term eye health. Both are fat-soluble, so take them with a meal that contains fat, and give them several weeks, since carotenoids build up in eye tissue gradually." },
  { a: "lutein", b: "bilberry", kind: "synergy", evidence: "emerging", summary: "Vision support.", detail: "Lutein protects the macula by filtering blue light and quenching oxidation, while bilberry's anthocyanins are traditionally used to support retinal blood flow and night vision, so the pair targets the eye's structure and its circulation.", advice: "A reasonable eye-health combination for screen users. Take lutein with a fatty meal for absorption, give it several weeks, and keep expectations realistic, as bilberry's classic night-vision reputation is only weakly supported by modern trials." },

  // ── Gut ──────────────────────────────────────────────────────────────────
  { a: "probiotic", b: "inulin", kind: "synergy", evidence: "moderate", summary: "Synbiotic: probiotic plus its food.", detail: "Inulin is a prebiotic fibre that the beneficial bacteria in a probiotic ferment for fuel, producing short-chain fatty acids that nourish the gut lining, so pairing them (a synbiotic) helps the cultures establish and feeds the bacteria you already have.", advice: "A classic gut pairing. Introduce inulin slowly and build up, since fermentable fibre can cause gas and bloating at first, and drink plenty of water. People with IBS or a FODMAP sensitivity may not tolerate inulin and should start very low." },
  { a: "probiotic", b: "s-boulardii", kind: "synergy", evidence: "moderate", summary: "Bacteria plus beneficial yeast.", detail: "S. boulardii is a friendly yeast rather than a bacterium, so it is not killed by antibiotics and works alongside bacterial probiotics, and it is best evidenced for preventing antibiotic-associated and traveller's diarrhoea.", advice: "A sensible combination, especially during and after antibiotics or while travelling. You can take S. boulardii at the same time as antibiotics, unlike bacterial probiotics, which are better spaced a couple of hours apart. Anyone immunocompromised or with a central line should check with a doctor first." },
  { a: "probiotic", b: "psyllium", kind: "synergy", evidence: "emerging", summary: "Probiotic plus fibre.", detail: "Psyllium is a gel-forming fibre that adds bulk and regularity, and a portion of it is fermented by gut bacteria, so it supports a healthy microbiome alongside the live cultures in a probiotic.", advice: "A reasonable pairing for regularity and gut health. Drink plenty of water with psyllium so it does not clump, and take it a couple of hours apart from any medication, since its gel can slow drug absorption." },
  { a: "zinc-carnosine", b: "dgl", kind: "synergy", evidence: "emerging", summary: "Gut-lining soothers.", detail: "Zinc-carnosine sticks to the stomach and gut lining and supports its repair, while DGL (deglycyrrhizinated licorice) increases protective mucus, so the two soothe and shield the lining through complementary mechanisms.", advice: "A common gut-repair pairing for indigestion or reflux-type discomfort. DGL has the blood-pressure-raising compound removed, making it safer for longer use than regular licorice. Take DGL before meals, and see a doctor for persistent stomach pain rather than self-treating." },
  { a: "l-glutamine", b: "zinc-carnosine", kind: "synergy", evidence: "emerging", summary: "Gut-lining support.", detail: "Glutamine is the main fuel for the cells lining the gut and supports the tight junctions between them, while zinc-carnosine adheres to the mucosa and aids its repair, so together they target the integrity of the gut barrier.", advice: "A reasonable gut-repair combination for people working on digestive comfort or barrier health. Glutamine is usually dosed at several grams daily; introduce it gradually, and check with a clinician if you have liver or kidney disease before taking high doses." },
  { a: "digestive-enzymes", b: "probiotic", kind: "synergy", evidence: "emerging", summary: "Digestion plus microbiome.", detail: "Digestive enzymes help break food down into absorbable pieces in the short term, while probiotics support the longer-term balance of gut bacteria, so one acts at the meal and the other on the ecosystem.", advice: "Fine to take together. Take digestive enzymes with or just before meals so they act on the food, and the probiotic whenever is consistent for you. If you frequently need enzymes to tolerate food, get the underlying cause checked by a clinician." },

  // ── Heart / metabolic ────────────────────────────────────────────────────
  { a: "red-yeast-rice", b: "coq10", kind: "synergy", evidence: "moderate", summary: "Red yeast rice can lower CoQ10.", detail: "Red yeast rice contains monacolin K, chemically the same as the statin lovastatin, and like statins it can deplete the body's CoQ10, the compound muscles use for energy, which is one proposed contributor to statin-type muscle aches.", advice: "Pairing CoQ10 (often as the better-absorbed ubiquinol) with red yeast rice is commonly recommended to offset that drop. More importantly, treat red yeast rice as a real statin: do not combine it with a prescription statin, and use it only with medical oversight and liver monitoring." },
  { a: "red-yeast-rice", b: "vit-b3", kind: "caution", evidence: "moderate", summary: "Two lipid agents on the liver.", detail: "Red yeast rice contains monacolin K, chemically the same as the statin lovastatin, and high-dose niacin (vitamin B3) is itself a lipid-lowering agent. Both are processed by the liver and together can raise liver enzymes and, rarely, cause muscle problems.", advice: "Do not stack these without medical supervision and periodic liver-enzyme and muscle monitoring. If you are already on a statin, treat red yeast rice as a duplicate and avoid adding it." },
  { a: "red-yeast-rice", b: "bergamot", kind: "synergy", evidence: "emerging", summary: "Complementary cholesterol support.", detail: "Both lower cholesterol but by different routes: red yeast rice's monacolin K blocks cholesterol production in the liver like a statin, while bergamot polyphenols nudge LDL and triglycerides down through separate mechanisms, so the effects can add up.", advice: "Discuss this with your doctor before combining, especially if you already take a statin, since red yeast rice is effectively a low-dose statin and stacking lipid-lowering agents needs monitoring. Recheck your cholesterol and liver enzymes after a few months." },
  { a: "berberine", b: "red-yeast-rice", kind: "synergy", evidence: "emerging", summary: "Lipid and glucose support.", detail: "Berberine improves insulin sensitivity and modestly lowers LDL, while red yeast rice blocks cholesterol synthesis in the liver like a statin, so together they target both the glucose and the lipid sides of cardiometabolic health.", advice: "Potentially useful but only under a clinician's eye: red yeast rice is essentially a statin, and berberine changes how the body processes many drugs. Monitor cholesterol, blood sugar, and liver enzymes, and do not combine it with a prescription statin." },
  { a: "berberine", b: "ala", kind: "synergy", evidence: "moderate", summary: "Blood-sugar pairing.", detail: "Berberine improves how cells respond to insulin and lowers blood glucose, while alpha-lipoic acid supports insulin sensitivity and reduces oxidative stress, including in diabetic nerve damage, so the two reinforce each other on blood-sugar control.", advice: "A reasonable metabolic-support pairing, but watch closely if you take diabetes medication, since both lower blood sugar and the combination can push it too low. Take ALA on an empty stomach, and review the plan with your doctor." },
  { a: "berberine", b: "milk-thistle", kind: "synergy", evidence: "emerging", summary: "Metabolic and liver support.", detail: "Both support cardiometabolic health, and milk thistle's silymarin may also raise berberine's notoriously poor absorption by slowing the gut transporter that pumps it back out, so milk thistle can act partly as an absorption helper.", advice: "A reasonable metabolic and liver-support combination. Be aware berberine affects how the body processes many drugs, so check with a pharmacist or doctor if you take regular medication, and monitor blood sugar if you are diabetic." },
  { a: "omega3", b: "bergamot", kind: "synergy", evidence: "emerging", summary: "Lipid-support pairing.", detail: "These hit different parts of the lipid panel: omega-3 fats mainly lower triglycerides, while bergamot polyphenols are studied for reducing LDL and total cholesterol, so combining them addresses more of the picture than either alone.", advice: "A complementary heart-support pairing. Take omega-3 with food for absorption, choose a fresh third-party-tested oil, and if your cholesterol is high enough to need treatment, use these alongside (not instead of) medical advice and recheck your levels." },
  { a: "hawthorn", b: "coq10", kind: "synergy", evidence: "emerging", summary: "Heart-function pairing.", detail: "Hawthorn is a traditional heart herb thought to support blood flow and the heart's pumping function, while CoQ10 fuels energy production in heart muscle, so both are used to support cardiac energy and function.", advice: "This is support, not treatment: check with a clinician before combining, particularly if you take heart or blood-pressure medication, since hawthorn can interact with them. Never use these in place of prescribed heart therapy." },
  { a: "chromium", b: "ala", kind: "synergy", evidence: "moderate", summary: "Glucose-metabolism pair.", detail: "Chromium helps insulin dock and move glucose into cells, while alpha-lipoic acid improves insulin sensitivity and lowers oxidative stress, so the two support blood-sugar handling through complementary mechanisms.", advice: "Useful for general metabolic support, but monitor closely if you are on diabetes medication, since the combination can lower blood sugar further. Take ALA on an empty stomach, and do not expect supplements to replace diet, exercise, or prescribed treatment." },

  // ── Bleeding cautions ────────────────────────────────────────────────────
  { a: "ginkgo", b: "nattokinase", kind: "caution", evidence: "moderate", summary: "Compounded blood-thinning effect.", detail: "Both reduce clotting through complementary routes, ginkgo by inhibiting platelet aggregation and nattokinase by breaking down fibrin. Together, or on top of an anticoagulant, the combined effect can push bleeding risk higher than either alone.", advice: "Avoid pairing these without a clinician's sign-off, especially if you take blood thinners, have a bleeding disorder, or have surgery scheduled. Stop both well before any procedure." },
  { a: "ginkgo", b: "aged-garlic", kind: "caution", evidence: "moderate", summary: "Both can thin the blood.", detail: "Ginkgo inhibits platelet aggregation and aged garlic has its own mild anti-platelet and blood-pressure-lowering effect, so the two can gently compound each other's thinning action.", advice: "Generally fine for healthy people at culinary or standard supplement doses. Use caution, and check with your doctor, if you take anticoagulants, have a bleeding disorder, or are heading into surgery." },
  { a: "nattokinase", b: "aged-garlic", kind: "caution", evidence: "moderate", summary: "Stacked clot effects.", detail: "Nattokinase breaks down fibrin while garlic is mildly anti-platelet, so combining them stacks two different clot-reducing mechanisms and can raise bleeding risk, particularly with anticoagulant medication.", advice: "Avoid combining if you take blood thinners or have a bleeding disorder, and pause both before surgery. Otherwise keep doses moderate and watch for warning signs such as easy bruising, bleeding gums, nosebleeds, or cuts that are slow to stop." },
  { a: "omega3", b: "aged-garlic", kind: "caution", evidence: "moderate", summary: "Mild additive thinning.", detail: "Both gently reduce platelet stickiness, omega-3 through its fatty acids and garlic through organosulfur compounds, so together they have a mild additive blood-thinning effect.", advice: "Fine for most people at normal doses and even helpful for heart health. Be cautious, and involve your doctor, if you are on blood thinners, have a clotting disorder, or have a procedure coming up." },

  // ── Adaptogen / stimulant cautions ───────────────────────────────────────
  { a: "rhodiola", b: "panax-ginseng", kind: "caution", evidence: "moderate", summary: "Two stimulating adaptogens.", detail: "Both rhodiola and panax ginseng are stimulating adaptogens that raise energy and alertness, so taken together they may overstimulate, cause jitteriness, or disrupt sleep, especially later in the day or at higher doses.", advice: "Take either one in the morning, start with low doses, and consider using just one rather than both. Avoid taking them in the afternoon or evening." },
  { a: "panax-ginseng", b: "theacrine", kind: "caution", evidence: "emerging", summary: "Stacked stimulation.", detail: "Both are stimulating: panax ginseng is an energising adaptogen and theacrine is a caffeine-like compound that raises alertness and focus. Taken together, especially later in the day, the combined stimulation can cause jitteriness, a faster heart rate, or trouble sleeping.", advice: "Keep this pairing to the morning and start with low doses of each. Watch your total daily stimulant load, including coffee and pre-workouts, and skip it if you are caffeine-sensitive or have a heart-rhythm concern." },
  { a: "theacrine", b: "green-tea", kind: "caution", evidence: "emerging", summary: "Layered stimulants.", detail: "Theacrine is a caffeine-like stimulant and green tea also contains caffeine, so stacking them adds to your total stimulant load and can tip you into jitteriness, anxiety, or disrupted sleep, particularly in slow caffeine metabolisers.", advice: "Mind your total daily caffeine across all sources. Take both earlier in the day, start low, and avoid the pairing in the afternoon or evening, or if you are caffeine-sensitive or pregnant." },
  { a: "rhodiola", b: "theacrine", kind: "caution", evidence: "emerging", summary: "Energising stack.", detail: "Rhodiola is an energising adaptogen and theacrine is a caffeine-like stimulant, so together they lift energy and focus from two directions and can easily overshoot into restlessness or poor sleep.", advice: "Use them in the morning only and begin with low doses. Consider whether you need both; if you keep the pair, account for any other caffeine you take that day." },

  // ── NAD+ / longevity ─────────────────────────────────────────────────────
  { a: "nmn", b: "nr", kind: "redundant", evidence: "moderate", summary: "Two NAD+ precursors.", detail: "NMN and NR are both NAD+ precursors that feed into the same salvage pathway to raise NAD+, so running both at once is largely overlapping and an expensive way to do one job.", advice: "Choose one rather than paying for both. NR has more human safety data; NMN is popular and well tolerated. Whichever you pick, consistency over months matters more than stacking." },
  { a: "resveratrol", b: "pterostilbene", kind: "redundant", evidence: "moderate", summary: "Pterostilbene is methylated resveratrol.", detail: "Pterostilbene is essentially a methylated version of resveratrol with the same family of effects but better absorption and a longer half-life, so the two heavily overlap.", advice: "Use one: pterostilbene for bioavailability, resveratrol for cost (and take resveratrol with fat to absorb it). Stacking both adds little beyond what one provides, and the longevity evidence for either remains preliminary in humans." },
  { a: "nmn", b: "resveratrol", kind: "synergy", evidence: "emerging", summary: "Popular longevity pairing.", detail: "NMN raises NAD+, the coenzyme that fuels cellular repair and energy, while resveratrol is theorised to activate sirtuin enzymes that depend on NAD+ to work, so the idea is that one supplies the fuel and the other switches on the machinery.", advice: "A common longevity stack, though the human evidence is still early and mostly extrapolated from animal and lab work. Take resveratrol with a fat-containing meal, since it absorbs poorly, and treat sweeping anti-aging claims with healthy skepticism." },
  { a: "fisetin", b: "quercetin", kind: "synergy", evidence: "emerging", summary: "Senolytic flavonoids.", detail: "Both are plant flavonoids studied as senolytics, compounds that may help clear worn-out 'senescent' cells that accumulate with age and drive inflammation. Because of that proposed hit-and-run action, researchers test them in short pulses rather than continuously.", advice: "Usually taken intermittently (for example a couple of high-dose days every so often) rather than daily, reflecting how the trials are run. The human evidence is early, so set modest expectations and check with a doctor if you take regular medication." },
  { a: "ca-akg", b: "nmn", kind: "synergy", evidence: "emerging", summary: "Longevity-stack pairing.", detail: "These target different proposed aging mechanisms: calcium alpha-ketoglutarate (Ca-AKG) is a metabolic intermediate studied for cellular energy and epigenetic aging, while NMN raises NAD+ for cellular repair, so the pair is combined to cover more than one pathway.", advice: "A reasonable longevity combination, but the human evidence is early for both. Treat it as an experiment rather than a proven protocol, prioritise the basics (sleep, exercise, diet) that have far stronger evidence, and check with a doctor if you take medication." },
  { a: "spermidine", b: "nmn", kind: "synergy", evidence: "emerging", summary: "Autophagy plus NAD+.", detail: "Spermidine is a compound (also found in foods like wheat germ and aged cheese) that may switch on autophagy, the cell's recycling and clean-up process, while NMN raises NAD+ for repair and energy, so the two target distinct longevity pathways.", advice: "A common longevity pairing, though human outcome data is limited. Spermidine can be obtained partly from diet, the evidence base is still building, and it is wise to keep expectations measured and check with a doctor before adding either if you take medication." },

  // ── Greens / general redundancy ──────────────────────────────────────────
  { a: "spirulina", b: "chlorella", kind: "redundant", evidence: "moderate", summary: "Overlapping green algae.", detail: "Both are nutrient-dense green algae with overlapping profiles of protein, chlorophyll, and minerals; the main difference is that chlorella has a tough cell wall (look for 'cracked-cell') and is promoted for binding metals, while spirulina is higher in protein.", advice: "One is usually enough unless you specifically want both profiles, and many greens products already blend them. Choose a brand that tests for heavy metals and toxins, since algae can concentrate contaminants from where it is grown." },
  { a: "quercetin", b: "zinc", kind: "synergy", evidence: "emerging", summary: "Quercetin helps zinc get into cells.", detail: "Zinc interferes with viral replication but struggles to get into cells on its own, and quercetin acts as a zinc ionophore, a shuttle that helps carry zinc through the cell membrane, which is the rationale behind the popular cold-season pairing.", advice: "A popular combination at the first sign of a cold. Take zinc with food to avoid nausea, keep it to about 40 mg a day at most and only short-term, and remember the human evidence for this specific pair is still emerging." },
  { a: "quercetin", b: "vit-c", kind: "synergy", evidence: "moderate", summary: "Antioxidant plus recycling.", detail: "Vitamin C helps regenerate quercetin after it neutralises a free radical, letting it keep working, and the two support immune function and histamine balance together, which is why allergy and immune formulas often pair them.", advice: "A common immune and allergy-season combination. Quercetin is poorly absorbed, so it is often sold with vitamin C or an enzyme to help; take it with food, and check with a doctor if you are on regular medication, as quercetin can affect drug metabolism." },
  { a: "elderberry", b: "zinc", kind: "synergy", evidence: "moderate", summary: "Cold-season pairing.", detail: "Elderberry's anthocyanins and zinc both act at the onset of a cold through different routes, zinc by hampering viral replication and elderberry by supporting the immune response, which is why they appear together in cold-season formulas.", advice: "A reasonable pairing taken at the first sign of a cold rather than year-round. Take zinc with food to avoid nausea and keep it short-term, and stop and see a doctor if a fever is high or symptoms drag on." },

  // ── Hormonal (men's / women's) ───────────────────────────────────────────
  { a: "zinc", b: "d-aspartic", kind: "synergy", evidence: "emerging", summary: "Testosterone-support pairing.", detail: "Zinc is required to make testosterone and a deficiency lowers it, so correcting low zinc can restore normal levels, while D-aspartic acid is an amino acid that may give a short-term signalling nudge to production.", advice: "Most of the benefit is in men who are genuinely zinc-deficient or start with low testosterone; in men with normal levels the effect is small and D-aspartic acid often fades within weeks. Take zinc with food, and do not exceed about 40 mg of zinc daily long-term." },
  { a: "boron", b: "d-aspartic", kind: "synergy", evidence: "emerging", summary: "Free-testosterone angle.", detail: "Boron can raise free testosterone by lowering the protein (SHBG) that binds it, and may also help through reduced inflammation, while D-aspartic acid targets the production side, so they approach testosterone from different angles.", advice: "Reasonable to combine, but keep expectations modest, since the effects are small and clearest in men who start low. Boron is taken in low doses (around 3 to 6 mg daily); there is no benefit to megadosing it." },
  { a: "tongkat-ali", b: "zinc", kind: "synergy", evidence: "emerging", summary: "Libido and testosterone support.", detail: "Tongkat ali (longjack) is studied for supporting free testosterone and lowering stress, while zinc covers a common dietary shortfall that itself limits testosterone, so the herb provides the push and zinc removes a possible brake.", advice: "A popular men's-health pairing. Take a standardised tongkat ali extract and keep zinc to a sensible dose with food. See a doctor for genuine low-testosterone symptoms rather than self-treating, since the real cause needs proper diagnosis." },
  { a: "tongkat-ali", b: "ashwagandha", kind: "synergy", evidence: "moderate", summary: "Testosterone and cortisol.", detail: "Tongkat ali supports androgens and libido, while ashwagandha lowers cortisol and stress, which itself can suppress testosterone, so the pair pushes testosterone up while easing a stress-related brake on it.", advice: "A common men's-vitality stack, taken daily and given several weeks. Take ashwagandha with food, check with a doctor if you have thyroid disease since ashwagandha can affect it, and get persistent low energy or libido medically assessed." },
  { a: "maca", b: "tongkat-ali", kind: "synergy", evidence: "emerging", summary: "Libido pairing.", detail: "Maca is a root studied for libido and energy that works without clearly changing hormone levels, while tongkat ali supports free testosterone, so the two come at sex drive and vitality from non-hormonal and hormonal directions.", advice: "A reasonable combination for libido and energy. Both need consistent daily use over weeks to judge; maca is usually taken as a few grams of powder. Effects vary a lot between people, so give it a fair trial before deciding." },
  { a: "saw-palmetto", b: "nettle-root", kind: "synergy", evidence: "moderate", summary: "Prostate-support pair.", detail: "Saw palmetto and nettle root are the two herbs most often combined for benign prostate enlargement: saw palmetto targets the hormone pathway behind prostate growth, while nettle root supports urinary flow, so they pair structure with symptoms.", advice: "A common prostate-formula pairing for urinary symptoms in older men. Trial evidence is mixed, so set realistic expectations and, importantly, get urinary symptoms checked by a doctor first, since they can signal conditions that need proper treatment." },
  { a: "saw-palmetto", b: "pumpkin-seed-oil", kind: "synergy", evidence: "emerging", summary: "Prostate and urinary support.", detail: "Both are used for benign prostate and urinary symptoms: saw palmetto acts on the hormone pathway that drives prostate growth, while pumpkin seed oil is thought to support bladder and pelvic-floor function, so they tackle the problem from two sides.", advice: "A reasonable pairing found in many men's prostate formulas. Give it several weeks, and see a doctor to rule out other causes of urinary symptoms before relying on supplements, especially with any blood, pain, or sudden change." },
  { a: "nettle-root", b: "pumpkin-seed-oil", kind: "synergy", evidence: "emerging", summary: "Urinary-support pair.", detail: "Nettle root supports urinary flow and prostate comfort, while pumpkin seed oil is used for bladder and pelvic-floor support, so the two are frequently combined in formulas aimed at the urinary symptoms of an enlarging prostate.", advice: "Often found together in men's urinary formulas. They are gentle and well tolerated, but persistent urinary symptoms warrant a medical check first, since an enlarged prostate is diagnosed and graded by a doctor and other causes need excluding." },
  { a: "chasteberry", b: "evening-primrose", kind: "synergy", evidence: "emerging", summary: "PMS-support pairing.", detail: "Chasteberry (vitex) acts on the brain's hormone signalling to support progesterone balance across the menstrual cycle, while evening primrose oil supplies the fatty acid GLA used for cyclical breast tenderness, so they target different PMS symptoms.", advice: "A traditional women's-health combination for PMS. Chasteberry needs a few cycles to judge and should be avoided in pregnancy or alongside hormonal medication without medical advice. See a clinician for severe or worsening symptoms." },
  { a: "black-cohosh", b: "evening-primrose", kind: "synergy", evidence: "emerging", summary: "Menopause-symptom support.", detail: "Black cohosh is used for menopausal hot flushes and night sweats, while evening primrose oil's GLA is taken for cyclical and breast symptoms, so the pair is combined for the overlapping discomforts of the menopause transition.", advice: "Discuss this with a clinician first, especially with a hormone-sensitive condition or liver concerns, since black cohosh has rare liver-safety reports. Give it several weeks, and treat heavy or unusual bleeding as a reason to see a doctor promptly." },

  // ── Liver ────────────────────────────────────────────────────────────────
  { a: "milk-thistle", b: "nac", kind: "synergy", evidence: "moderate", summary: "Liver-support pair.", detail: "Milk thistle's silymarin helps protect and stabilise liver cells against damage, while NAC supplies cysteine to rebuild glutathione, the liver's main detox antioxidant (and the antidote hospitals use for paracetamol overdose), so they support the liver from two angles.", advice: "A common liver-support combination, generally well tolerated. It supports a healthy liver but is not a treatment for liver disease, so get persistent symptoms or abnormal liver tests properly investigated, and take NAC away from any nitrate heart medication." },
  { a: "tudca", b: "milk-thistle", kind: "synergy", evidence: "emerging", summary: "Bile and liver-cell support.", detail: "TUDCA is a bile acid that supports healthy bile flow and helps protect liver cells under stress, while milk thistle's silymarin guards liver cells against oxidative damage, so the pair covers both bile flow and cell protection.", advice: "A reasonable liver pairing used by some on demanding regimens. Evidence in healthy people is limited, so treat it as support rather than therapy, and see a doctor for jaundice, itching, or abnormal liver tests instead of self-treating." },
  { a: "artichoke", b: "milk-thistle", kind: "synergy", evidence: "emerging", summary: "Liver and bile support.", detail: "Artichoke leaf stimulates bile production and flow, which aids fat digestion, while milk thistle protects liver cells, so the two are traditionally combined for liver and digestive support, especially after rich meals.", advice: "A traditional liver-and-digestion combination that is gentle for most people. Avoid artichoke if you have bile-duct obstruction or gallstones, since stimulating bile can cause problems there, and check with a doctor if you have gallbladder disease." },
  { a: "dandelion", b: "milk-thistle", kind: "synergy", evidence: "emerging", summary: "Traditional liver/detox pair.", detail: "Dandelion root is a traditional bitter that supports bile flow and digestion, while milk thistle protects liver cells, so the two are paired in classic liver and detox formulas, though modern evidence is thin.", advice: "A gentle traditional pairing. Dandelion is mildly diuretic and can interact with lithium or some blood-pressure drugs, and should be avoided with bile-duct blockage, so check with a doctor if you take regular medication or have gallbladder issues." },

  // ── Vitamin D ecosystem ──────────────────────────────────────────────────
  { a: "d3k2", b: "calcium", kind: "synergy", evidence: "strong", summary: "Vitamin D drives calcium absorption.", detail: "Vitamin D3 increases how much calcium you absorb from the gut, and vitamin K2 activates the proteins that steer that calcium into bone and away from arteries, so the three work as a bone-health team rather than calcium alone.", advice: "A sensible bone-health combination, take D3+K2 with a meal containing fat. Do not over-supplement calcium; food-first is best, and high isolated calcium without K2 and D is the pattern to avoid." },
  { a: "d3k2", b: "boron", kind: "synergy", evidence: "emerging", summary: "Boron supports vitamin D status.", detail: "Boron appears to slow the breakdown of active vitamin D, helping levels stay higher for longer, and it also supports how the body handles calcium and magnesium, the minerals vitamin D and K2 work with for bone.", advice: "A reasonable bone-and-hormone pairing on top of D3 plus K2. Boron is taken in small amounts (around 3 mg daily); more is not better. Take D3 and K2 with a fat-containing meal, since all are fat-soluble." },
  { a: "calcium", b: "vit-k2", kind: "synergy", evidence: "moderate", summary: "K2 directs calcium to bone.", detail: "Vitamin K2 activates two proteins, osteocalcin and matrix-Gla protein, that pull calcium into bone and help keep it out of artery walls, so K2 helps steer supplemental calcium toward the skeleton rather than soft tissue.", advice: "If you supplement calcium, pairing it with K2 (and vitamin D, which drives absorption) is sensible. Better still, favour calcium from food, keep doses moderate, and check with your doctor before high-dose calcium, especially with heart or kidney issues." },
  { a: "vit-a", b: "d3k2", kind: "synergy", evidence: "emerging", summary: "Fat-soluble vitamins balance each other.", detail: "Vitamins A, D, and K are fat-soluble partners that influence each other: vitamin D and A share receptor machinery and can blunt each other's toxicity, while K2 directs the calcium that vitamin D helps absorb, so balance among them matters more than loading any one.", advice: "Modest doses together are reasonable and reflect how these vitamins occur in foods like liver, egg yolk, and dairy. Avoid high-dose vitamin A in pregnancy, where excess is harmful, and take the group with a fat-containing meal for absorption." },

  // ── Performance & focus ──────────────────────────────────────────────────
  { a: "caffeine", b: "l-theanine", kind: "synergy", evidence: "strong", summary: "The classic calm-focus stack.", detail: "Caffeine raises alertness but can bring jitters and a crash, while L-theanine promotes calm focus without sedation; together they smooth caffeine's edge and improve attention and reaction time better than either alone.", advice: "A popular ratio is about 100 mg caffeine to 200 mg L-theanine. Take it in the morning or before focused work, and keep caffeine before mid-afternoon so it does not disturb sleep." },
  { a: "rhodiola", b: "caffeine", kind: "caution", evidence: "moderate", summary: "Two stimulating compounds stack up.", detail: "Rhodiola is mildly stimulating and fights fatigue, and caffeine is a direct stimulant, so taken together they can add up to jitteriness, a racing heart, or anxiety in sensitive people.", advice: "If you use both, keep caffeine modest and take them earlier in the day. Start with lower doses to see how you react, and avoid the combination late in the afternoon to protect sleep." },
  { a: "l-tyrosine", b: "caffeine", kind: "synergy", evidence: "moderate", summary: "Focus support under pressure.", detail: "L-tyrosine is the raw material for dopamine and noradrenaline, the focus-and-drive chemicals that stress and stimulants draw down, so pairing it with caffeine may help sustain attention during demanding or sleep-short stretches.", advice: "Common amounts are 500 to 2000 mg tyrosine with your usual caffeine, on an empty stomach before mentally demanding work. Keep caffeine before mid-afternoon to protect sleep." },
  { a: "whey-isolate", b: "creatine", kind: "synergy", evidence: "strong", summary: "Cornerstone muscle-building pair.", detail: "Whey supplies fast-digesting protein and leucine to drive muscle protein synthesis, while creatine increases the energy available for hard sets and adds cell hydration, so together they support strength and lean mass better than either alone.", advice: "A simple approach is 20 to 40 g whey plus 3 to 5 g creatine daily, often together after training, though timing matters less than hitting your daily totals. Creatine works best taken every day, not only on workout days." },
  { a: "glucosamine", b: "chondroitin", kind: "synergy", evidence: "moderate", summary: "The classic joint duo.", detail: "Glucosamine and chondroitin are both building blocks of cartilage that are almost always studied and sold together; the combination is thought to support the cartilage matrix and has the most evidence in moderate knee osteoarthritis.", advice: "Typical doses are 1500 mg glucosamine and 1200 mg chondroitin daily, often split. Give it 8 to 12 weeks to judge, and skip glucosamine sourced from shellfish if you have a shellfish allergy." },
  { a: "berberine", b: "cinnamon", kind: "synergy", evidence: "moderate", summary: "Blood-sugar support from two angles.", detail: "Berberine activates an enzyme called AMPK to improve insulin sensitivity and lower blood sugar, while Ceylon cinnamon slows carbohydrate digestion and modestly improves fasting glucose, so the two support healthy blood sugar by different mechanisms.", advice: "Berberine is usually 500 mg two to three times daily with meals; cinnamon around 1 to 2 g of the Ceylon type. If you take blood-sugar or diabetes medication, monitor closely and involve your doctor, since the combination can lower glucose meaningfully." },
];

/** Canonical slug for a pair, order-independent. */
export function interactionSlug(a: string, b: string): string {
  return [a, b].sort().join("-and-");
}

/** Find an interaction by two ids, in either order. */
export function findInteraction(a: string, b: string): Interaction | undefined {
  return INTERACTIONS.find(i => (i.a === a && i.b === b) || (i.a === b && i.b === a));
}

/** Find an interaction by its canonical slug. */
export function interactionBySlug(slug: string): Interaction | undefined {
  return INTERACTIONS.find(i => interactionSlug(i.a, i.b) === slug);
}

/** Unique on-page copy length (summary + detail + advice), in words. */
export function interactionWordCount(it: Interaction): number {
  return `${it.summary} ${it.detail} ${it.advice}`.trim().split(/\s+/).filter(Boolean).length;
}

/**
 * Single source of truth for "is this interaction page substantive enough to
 * index?". Used by BOTH the page noindex gate and the sitemap so they cannot
 * drift (the QA audit caught the sitemap submitting noindexed pages).
 */
export const INTERACTION_MIN_WORDS = 60;
export function interactionIndexable(it: Interaction): boolean {
  return interactionWordCount(it) >= INTERACTION_MIN_WORDS;
}
