// AUTO-GENERATED on 2026-06-05 from PubMed E-utilities (esearch).
// Each count = real number of randomized controlled trials, meta-analyses, and
// systematic reviews indexed on PubMed for that supplement-intervention query.
// Verifiable: every ingredient page links to the exact same PubMed search.
// Source data (auditable): scripts/research-volume.source.tsv  (id, query term, PubMed count).
export interface ResearchVolume { term: string; count: number }

export const RESEARCH_VOLUME: Record<string, ResearchVolume> = {
  "d3k2": { term: "Vitamin D3 supplementation", count: 1992 },
  "omega3": { term: "Omega-3 supplementation", count: 2813 },
  "omega3-algae": { term: "Algae Omega-3 supplementation", count: 17 },
  "multivit": { term: "Multivitamin supplementation", count: 424 },
  "mag-glycinate": { term: "Magnesium supplementation", count: 666 },
  "ashwagandha": { term: "Ashwagandha", count: 112 },
  "l-theanine": { term: "L-Theanine supplementation", count: 12 },
  "glycine": { term: "Glycine supplementation", count: 342 },
  "b12": { term: "Vitamin B12 supplementation", count: 692 },
  "b-complex": { term: "Vitamin B Complex supplementation", count: 1850 },
  "rhodiola": { term: "Rhodiola", count: 92 },
  "lions-mane": { term: "Hericium erinaceus", count: 12 },
  "creatine": { term: "Creatine", count: 4284 },
  "collagen": { term: "Collagen supplementation", count: 462 },
  "curcumin": { term: "Curcumin", count: 1081 },
  "glucosamine": { term: "Glucosamine", count: 460 },
  "vit-c": { term: "Vitamin C supplementation", count: 1147 },
  "zinc": { term: "Zinc supplementation", count: 1550 },
  "elderberry": { term: "Elderberry", count: 38 },
  "probiotic": { term: "Multi-Strain Probiotic", count: 170 },
  "digestive-enzymes": { term: "Digestive Enzymes", count: 3890 },
  "iron": { term: "Iron supplementation", count: 1962 },
  "coq10": { term: "Coenzyme Q10", count: 751 },
  "biotin": { term: "Biotin supplementation", count: 36 },
  "nac": { term: "N-Acetyl Cysteine supplementation", count: 139 },
  "taurine": { term: "Taurine supplementation", count: 133 },
  "acetyl-l-carnitine": { term: "Acetyl-L-Carnitine supplementation", count: 39 },
  "l-carnitine": { term: "L-Carnitine Tartrate supplementation", count: 20 },
  "ala": { term: "Alpha-Lipoic Acid", count: 420 },
  "berberine": { term: "Berberine", count: 244 },
  "quercetin": { term: "Quercetin", count: 505 },
  "resveratrol": { term: "Resveratrol", count: 576 },
  "pqq": { term: "Pyrroloquinoline quinone", count: 11 },
  "ubiquinol": { term: "Ubiquinol", count: 60 },
  "mag-citrate": { term: "Magnesium supplementation", count: 666 },
  "mag-threonate": { term: "Magnesium L-Threonate supplementation", count: 1 },
  "vit-k2": { term: "Vitamin K2 MK-7 supplementation", count: 26 },
  "selenium": { term: "Selenium supplementation", count: 838 },
  "iodine": { term: "Iodine supplementation", count: 212 },
  "chromium": { term: "Chromium supplementation", count: 174 },
  "boron": { term: "Boron supplementation", count: 15 },
  "inositol": { term: "Inositol", count: 720 },
  "melatonin": { term: "Melatonin", count: 1956 },
  "5-htp": { term: "5-HTP", count: 114 },
  "valerian": { term: "Valerian", count: 108 },
  "saffron": { term: "Saffron", count: 249 },
  "holy-basil": { term: "Holy Basil", count: 18 },
  "panax-ginseng": { term: "Korean Red Ginseng", count: 503 },
  "bacopa": { term: "Bacopa Monnieri", count: 35 },
  "ginkgo": { term: "Ginkgo Biloba", count: 580 },
  "citicoline": { term: "Citicoline", count: 155 },
  "alpha-gpc": { term: "Alpha-GPC", count: 6 },
  "phosphatidylserine": { term: "Phosphatidylserine", count: 111 },
  "astaxanthin": { term: "Astaxanthin", count: 130 },
  "lutein": { term: "Lutein", count: 474 },
  "msm": { term: "MSM", count: 1061 },
  "boswellia": { term: "Boswellia", count: 113 },
  "l-glutamine": { term: "L-Glutamine supplementation", count: 425 },
  "milk-thistle": { term: "Milk Thistle", count: 113 },
  "spirulina": { term: "Spirulina", count: 151 },
  "chlorella": { term: "Chlorella", count: 54 },
  "beetroot": { term: "Beetroot", count: 429 },
  "l-citrulline": { term: "L-Citrulline", count: 325 },
  "beta-alanine": { term: "Beta-Alanine", count: 578 },
  "mct-oil": { term: "MCT", count: 844 },
  "tongkat-ali": { term: "Tongkat Ali", count: 16 },
  "maca": { term: "Maca", count: 47 },
  "cordyceps": { term: "Cordyceps", count: 57 },
  "reishi": { term: "Reishi", count: 35 },
  "methylfolate": { term: "Methylfolate supplementation", count: 7 },
  "vit-a": { term: "Vitamin A supplementation", count: 977 },
  "vit-e": { term: "Vitamin E supplementation", count: 1493 },
  "phosphatidylcholine": { term: "Phosphatidylcholine", count: 615 },
  "choline": { term: "Choline Bitartrate supplementation", count: 169 },
  "vit-b6": { term: "Vitamin B6 supplementation", count: 345 },
  "vit-b1": { term: "Thiamine supplementation", count: 130 },
  "vit-b3": { term: "Niacinamide supplementation", count: 46 },
  "vit-b2": { term: "Riboflavin supplementation", count: 135 },
  "zma": { term: "Zinc Magnesium Aspartate", count: 7 },
  "lithium-orotate": { term: "Lithium orotate supplementation", count: 0 },
  "fenugreek": { term: "Fenugreek", count: 103 },
  "dim": { term: "Diindolylmethane", count: 12 },
  "saw-palmetto": { term: "Saw Palmetto", count: 127 },
  "evening-primrose": { term: "Evening Primrose supplementation", count: 39 },
  "cranberry": { term: "Cranberry", count: 276 },
  "hawthorn": { term: "Hawthorn Berry", count: 21 },
  "aged-garlic": { term: "Aged garlic extract", count: 94 },
  "nattokinase": { term: "Nattokinase", count: 11 },
  "psyllium": { term: "Psyllium Husk", count: 33 },
  "inulin": { term: "Inulin", count: 657 },
  "ginger": { term: "Ginger", count: 537 },
  "green-tea": { term: "Green Tea EGCG", count: 127 },
  "l-tyrosine": { term: "Tyrosine supplementation", count: 138 },
  "tudca": { term: "TUDCA", count: 29 },
  "whey-isolate": { term: "Whey Protein Isolate", count: 162 },
  "plant-protein": { term: "Plant Protein Blend", count: 57 },
  "dha-prenatal": { term: "Docosahexaenoic acid supplementation", count: 1346 },
  "bcaa": { term: "BCAAs", count: 153 },
  "eaa": { term: "Essential Amino Acids", count: 5877 },
  "moringa": { term: "Moringa", count: 79 },
  "nmn": { term: "Nicotinamide Mononucleotide", count: 29 },
  "nr": { term: "Nicotinamide Riboside", count: 36 },
  "fisetin": { term: "Fisetin", count: 21 },
  "urolithin-a": { term: "Urolithin A", count: 31 },
  "spermidine": { term: "Spermidine", count: 51 },
  "ca-akg": { term: "Alpha-ketoglutarate", count: 210 },
  "apigenin": { term: "Apigenin", count: 57 },
  "pterostilbene": { term: "Pterostilbene", count: 10 },
  "tmg": { term: "Betaine supplementation", count: 107 },
  "tributyrin": { term: "Tributyrin", count: 3 },
  "lactoferrin": { term: "Lactoferrin", count: 406 },
  "s-boulardii": { term: "Saccharomyces boulardii", count: 196 },
  "dgl": { term: "Licorice", count: 241 },
  "zinc-carnosine": { term: "Zinc-Carnosine", count: 36 },
  "theacrine": { term: "Theacrine", count: 12 },
  "uridine": { term: "Uridine Monophosphate", count: 228 },
  "pycnogenol": { term: "Pycnogenol", count: 91 },
  "huperzine": { term: "Huperzine A", count: 35 },
  "hyaluronic-acid": { term: "Hyaluronic Acid supplementation", count: 44 },
  "tocotrienols": { term: "Tocotrienols supplementation", count: 56 },
  "silica": { term: "Silicon supplementation", count: 15 },
  "ceramides": { term: "Ceramides", count: 277 },
  "hmb": { term: "HMB", count: 333 },
  "tart-cherry": { term: "Tart Cherry", count: 73 },
  "l-arginine": { term: "L-Arginine supplementation", count: 568 },
  "d-aspartic": { term: "D-Aspartic Acid", count: 45 },
  "tribulus": { term: "Tribulus Terrestris", count: 50 },
  "tryptophan": { term: "L-Tryptophan supplementation", count: 132 },
  "magnolia-bark": { term: "Magnolia", count: 126 },
  "passionflower": { term: "Passionflower", count: 47 },
  "lemon-balm": { term: "Lemon Balm", count: 456 },
  "gaba": { term: "GABA supplementation", count: 65 },
  "bergamot": { term: "Citrus Bergamot", count: 20 },
  "red-yeast-rice": { term: "Red Yeast Rice", count: 104 },
  "bilberry": { term: "Bilberry", count: 51 },
  "dandelion": { term: "Dandelion", count: 13 },
  "artichoke": { term: "Artichoke", count: 73 },
  "chasteberry": { term: "Chasteberry", count: 58 },
  "black-cohosh": { term: "Black Cohosh", count: 93 },
  "nettle-root": { term: "Nettle", count: 71 },
  "pumpkin-seed-oil": { term: "Pumpkin", count: 51 },
  "white-willow": { term: "White Willow", count: 297 },
  "glutathione": { term: "Glutathione supplementation", count: 869 },
  "astragalus": { term: "Astragalus", count: 492 },
  "mucuna": { term: "Mucuna Pruriens", count: 13 },
  "eleuthero": { term: "Eleuthero", count: 39 },
  "schisandra": { term: "Schisandra Berry", count: 6 },
  "chaga": { term: "Chaga", count: 902 },
  "potassium": { term: "Potassium supplementation", count: 391 },
  "calcium": { term: "Calcium supplementation", count: 2561 },
  "turkey-tail": { term: "Turkey Tail", count: 10 },
  "tremella": { term: "Tremella", count: 3 },
  "oregano-oil": { term: "Oregano", count: 55 },
  "olive-leaf": { term: "Olive leaf", count: 43 },
  "sulforaphane": { term: "Sulforaphane", count: 108 },
  "gotu-kola": { term: "Gotu Kola", count: 77 },
  "maitake": { term: "Maitake", count: 9 },
  "agmatine": { term: "Agmatine", count: 10 },
  "carnosine": { term: "L-Carnosine", count: 203 },
  "l-ornithine": { term: "L-Ornithine supplementation", count: 47 },
  "gymnema": { term: "Gymnema Sylvestre", count: 24 },
  "cinnamon": { term: "Ceylon Cinnamon", count: 116 },
  "shatavari": { term: "Shatavari", count: 9 },
  "echinacea": { term: "Echinacea", count: 114 },
  "andrographis": { term: "Andrographis paniculata", count: 45 },
  "shilajit": { term: "Shilajit", count: 9 },
  "caffeine": { term: "Caffeine", count: 2890 },
  "sam-e": { term: "SAM-e", count: 184 },
  "st-johns-wort": { term: "St. Johns Wort", count: 316 },
  "chamomile": { term: "Chamomile", count: 171 },
  "grape-seed": { term: "Grape", count: 568 },
  "green-coffee-bean": { term: "Green Coffee Bean", count: 21 },
  "glucomannan": { term: "Glucomannan", count: 80 },
  "apple-cider-vinegar": { term: "Apple Cider Vinegar", count: 11 },
  "betaine-hcl": { term: "Betaine", count: 294 },
  "colostrum": { term: "Bovine Colostrum", count: 240 },
  "dhea": { term: "DHEA", count: 1050 },
  "d-mannose": { term: "D-Mannose", count: 234 },
  "bromelain": { term: "Bromelain", count: 110 },
  "serrapeptase": { term: "Serrapeptase", count: 16 },
  "l-lysine": { term: "L-Lysine supplementation", count: 104 },
  "black-seed-oil": { term: "Nigella sativa", count: 186 },
  "sea-moss": { term: "Sea Moss", count: 3 },
  "beta-sitosterol": { term: "Beta-Sitosterol", count: 134 },
  "pygeum": { term: "Pygeum", count: 11 },
  "calcium-d-glucarate": { term: "Calcium D-Glucarate", count: 150 },
  "horny-goat-weed": { term: "Horny Goat Weed", count: 4 },
  "propolis": { term: "Bee Propolis", count: 243 },
  "devils-claw": { term: "Devils Claw", count: 23 },
  "chondroitin": { term: "Chondroitin", count: 484 },
  "lycopene": { term: "Lycopene", count: 486 },
  "feverfew": { term: "Feverfew", count: 21 },
  "horse-chestnut": { term: "Horse Chestnut", count: 0 },
  "aloe-vera": { term: "Aloe Vera", count: 320 },
  "slippery-elm": { term: "Slippery Elm", count: 4 },
  "lavender": { term: "Lavender", count: 538 },
  "cats-claw": { term: "Cats Claw", count: 18 },
  "pomegranate": { term: "Pomegranate", count: 240 },
  "bitter-melon": { term: "Bitter Melon", count: 37 },
  "dong-quai": { term: "Dong Quai", count: 35 },
  "DONE rows=201": { term: "", count: 0 },
};

export const RESEARCH_VOLUME_AS_OF = "2026-06-05";
/** Studies summed across UNIQUE search terms (shared cores like Magnesium counted once). */
export const RESEARCH_STUDY_TOTAL = 71776;

const PUBMED_FILTER = "(randomizedcontrolledtrial[Filter] OR meta-analysis[Filter] OR systematicreview[Filter])";
/** Verifiable PubMed link for a term: the exact query behind its count. */
export function pubmedUrl(term: string): string {
  return `https://pubmed.ncbi.nlm.nih.gov/?term=${encodeURIComponent(`${term} AND ${PUBMED_FILTER}`)}`;
}
/** Count + verifiable link for one ingredient id (null if not catalogued). */
export function researchVolume(id: string): (ResearchVolume & { url: string }) | null {
  const v = RESEARCH_VOLUME[id];
  return v ? { ...v, url: pubmedUrl(v.term) } : null;
}
