/**
 * Curated clinical-research database for supplement ingredients.
 *
 * Each entry references real published research, paraphrasing the key finding
 * in plain English. We link to PubMed search URLs (always-resolving) rather
 * than fragile direct PMID/DOI links unless we're highly confident.
 *
 * Coverage: ~30 of the most-searched ingredients, with deeper coverage for
 * the foundational stack. Supplements without an entry fall back to a
 * PubMed search auto-built from their name.
 */

export type StudyType = "RCT" | "Meta-analysis" | "Cohort" | "Systematic Review" | "Pilot RCT" | "Mechanistic";

export interface Study {
  title: string;
  authors: string;          // "Smith et al." or full citation
  journal: string;
  year: number;
  type: StudyType;
  sample: string;           // "n=126 healthy adults" / "60 RCTs pooled"
  dose: string;             // "5,000 IU/day" or "—" if not applicable
  duration: string;         // "12 weeks" or "—"
  finding: string;          // 1-2 sentences, plain English
  pubmedQuery: string;      // search query that resolves on PubMed
  pmid?: string;            // optional, used to build a direct link when confident
}

export interface ResearchEntry {
  ingredient: string;          // matches supplement.id
  evidenceLevel: "very strong" | "strong" | "moderate" | "emerging";
  summary: string;             // 2-3 sentence overview of the literature
  bestUseCases: string[];      // 3-5 short bullets
  studies: Study[];
}

const pm = (q: string) => q.split(/\s+/).join("+");

// ─── Research database (top 30 supplements) ──────────────────────────────
export const RESEARCH: Record<string, ResearchEntry> = {

  d3k2: {
    ingredient: "d3k2",
    evidenceLevel: "very strong",
    summary: "Vitamin D3 is one of the most-studied supplements in human history — over 90,000 published papers. The combination with K2 directs supplemental calcium into bones and away from arteries.",
    bestUseCases: ["Correct low serum 25(OH)D", "Bone density support", "Immune resilience (especially in winter)", "Mood support in low-sun seasons", "Cardiovascular calcium routing (with K2)"],
    studies: [
      {
        title: "Vitamin D and mortality: meta-analysis of randomized clinical trials",
        authors: "Bjelakovic et al.",
        journal: "Cochrane Database of Systematic Reviews",
        year: 2014,
        type: "Meta-analysis",
        sample: "56 RCTs · 95,286 participants",
        dose: "300–2,000 IU/day",
        duration: "≥1 year",
        finding: "Vitamin D3 (not D2) supplementation reduced all-cause mortality by 6% (RR 0.94). The effect was consistent across age groups.",
        pubmedQuery: pm("vitamin D3 mortality meta-analysis Bjelakovic"),
      },
      {
        title: "Effects of vitamin D supplementation on respiratory tract infections",
        authors: "Martineau et al.",
        journal: "BMJ",
        year: 2017,
        type: "Meta-analysis",
        sample: "25 RCTs · 11,321 participants",
        dose: "Daily or weekly",
        duration: "Varied",
        finding: "Daily/weekly vitamin D reduced acute respiratory infection risk (OR 0.81). Strongest in those most deficient at baseline.",
        pubmedQuery: pm("vitamin D respiratory infection Martineau BMJ"),
      },
      {
        title: "Vitamin K2 and bone density in postmenopausal women",
        authors: "Knapen et al.",
        journal: "Osteoporosis International",
        year: 2013,
        type: "RCT",
        sample: "244 postmenopausal women",
        dose: "180 mcg MK-7/day",
        duration: "3 years",
        finding: "MK-7 supplementation significantly reduced age-related loss in vertebral and hip bone mineral content vs placebo.",
        pubmedQuery: pm("vitamin K2 MK-7 bone density postmenopausal Knapen"),
      },
      {
        title: "Vitamin D and depressive symptoms: meta-analysis",
        authors: "Cheng et al.",
        journal: "Depression and Anxiety",
        year: 2020,
        type: "Meta-analysis",
        sample: "25 RCTs",
        dose: "≥800 IU/day",
        duration: "8+ weeks",
        finding: "Vitamin D supplementation produced significant improvements in depressive symptoms vs placebo (SMD -0.49) in adults with low baseline status.",
        pubmedQuery: pm("vitamin D depression meta-analysis"),
      },
    ],
  },

  omega3: {
    ingredient: "omega3",
    evidenceLevel: "very strong",
    summary: "Omega-3 fatty acids (EPA + DHA) are the single most-studied supplement category for cardiovascular disease, inflammation, and brain function. The triglyceride form is more bioavailable than ethyl esters.",
    bestUseCases: ["Cardiovascular disease prevention", "Triglyceride reduction", "Mood support (especially depression)", "Pregnancy / fetal brain development", "Joint inflammation"],
    studies: [
      {
        title: "Marine omega-3 supplementation and cardiovascular disease",
        authors: "Hu et al.",
        journal: "Journal of the American Heart Association",
        year: 2019,
        type: "Meta-analysis",
        sample: "13 RCTs · 127,477 participants",
        dose: "0.4–4 g/day EPA+DHA",
        duration: "Mean 5 years",
        finding: "Omega-3 supplementation reduced fatal myocardial infarction risk by 8% (RR 0.92), with dose-response: higher doses produced larger effects.",
        pubmedQuery: pm("omega 3 cardiovascular meta-analysis Hu JAHA"),
      },
      {
        title: "Omega-3 polyunsaturated fatty acids and depression",
        authors: "Liao et al.",
        journal: "Translational Psychiatry",
        year: 2019,
        type: "Meta-analysis",
        sample: "26 RCTs · 2,160 participants",
        dose: "≥60% EPA-dominant",
        duration: "8–12 weeks",
        finding: "EPA-dominant omega-3 (≥60% EPA) significantly reduced depression symptoms (SMD -0.99) vs placebo. DHA-only formulations were ineffective.",
        pubmedQuery: pm("omega 3 EPA depression Liao meta-analysis"),
      },
      {
        title: "Effect of omega-3 fatty acids on serum triglycerides",
        authors: "Skulas-Ray et al.",
        journal: "Circulation",
        year: 2019,
        type: "Systematic Review",
        sample: "Pooled clinical data",
        dose: "2–4 g/day",
        duration: "8+ weeks",
        finding: "AHA scientific statement: 4 g/day EPA+DHA produces 20–30% reduction in serum triglycerides, comparable to fibrate medications.",
        pubmedQuery: pm("omega 3 triglycerides Skulas-Ray AHA"),
      },
      {
        title: "Omega-3 and rheumatoid arthritis joint symptoms",
        authors: "Goldberg & Katz",
        journal: "Pain",
        year: 2007,
        type: "Meta-analysis",
        sample: "17 RCTs · 823 patients",
        dose: "2.7+ g/day EPA+DHA",
        duration: "≥3 months",
        finding: "Fish oil supplementation reduced joint pain intensity, morning stiffness, and NSAID consumption in inflammatory arthritis.",
        pubmedQuery: pm("fish oil rheumatoid arthritis Goldberg Katz"),
      },
    ],
  },

  "mag-glycinate": {
    ingredient: "mag-glycinate",
    evidenceLevel: "strong",
    summary: "Magnesium is involved in over 300 enzyme reactions and is one of the most-deficient nutrients globally. Glycinate is the most-evidenced form for sleep, stress, and long-term repletion.",
    bestUseCases: ["Sleep onset and depth", "Stress and anxiety reduction", "Muscle cramps / restless legs", "Long-term magnesium repletion without GI side effects", "Blood pressure modulation"],
    studies: [
      {
        title: "Magnesium supplementation for insomnia in elderly subjects",
        authors: "Abbasi et al.",
        journal: "Journal of Research in Medical Sciences",
        year: 2012,
        type: "RCT",
        sample: "46 older adults with insomnia",
        dose: "500 mg/day elemental Mg",
        duration: "8 weeks",
        finding: "Magnesium significantly improved sleep efficiency, sleep time, sleep onset latency, and morning serum cortisol vs placebo.",
        pubmedQuery: pm("magnesium insomnia elderly Abbasi"),
      },
      {
        title: "Magnesium status and anxiety: systematic review",
        authors: "Boyle et al.",
        journal: "Nutrients",
        year: 2017,
        type: "Systematic Review",
        sample: "18 studies pooled",
        dose: "Various",
        duration: "Varied",
        finding: "Subjective anxiety improvements were consistently observed across magnesium supplementation trials, especially in subjects with low baseline status.",
        pubmedQuery: pm("magnesium anxiety systematic review Boyle Nutrients"),
      },
      {
        title: "Magnesium intake and risk of type 2 diabetes",
        authors: "Larsson & Wolk",
        journal: "Journal of Internal Medicine",
        year: 2007,
        type: "Meta-analysis",
        sample: "286,668 participants",
        dose: "Dietary",
        duration: "4–18 year follow-up",
        finding: "Each 100 mg/day increase in magnesium intake reduced type 2 diabetes risk by 15%.",
        pubmedQuery: pm("magnesium diabetes Larsson Wolk"),
      },
      {
        title: "Magnesium and blood pressure",
        authors: "Zhang et al.",
        journal: "Hypertension",
        year: 2016,
        type: "Meta-analysis",
        sample: "34 RCTs · 2,028 participants",
        dose: "Median 368 mg/day",
        duration: "Median 3 months",
        finding: "Magnesium supplementation reduced systolic BP by 2.00 mmHg and diastolic by 1.78 mmHg, with stronger effects at higher doses.",
        pubmedQuery: pm("magnesium blood pressure Zhang meta-analysis Hypertension"),
      },
    ],
  },

  ashwagandha: {
    ingredient: "ashwagandha",
    evidenceLevel: "strong",
    summary: "Ashwagandha (Withania somnifera) is the most-studied adaptogen, with KSM-66 as the most-validated standardised extract. The strongest evidence is for chronic stress, cortisol reduction, and sleep.",
    bestUseCases: ["Chronic stress with elevated cortisol", "Sleep onset difficulties from anxiety", "Anxiety and overwhelm", "Athletic performance and recovery", "Mild low mood"],
    studies: [
      {
        title: "Efficacy and safety of ashwagandha root extract in stress",
        authors: "Chandrasekhar et al.",
        journal: "Indian Journal of Psychological Medicine",
        year: 2012,
        type: "RCT",
        sample: "64 chronically stressed adults",
        dose: "300 mg KSM-66 twice daily",
        duration: "60 days",
        finding: "Ashwagandha produced a 27.9% reduction in serum cortisol and significant improvements across all measured stress assessment scales vs placebo.",
        pubmedQuery: pm("ashwagandha stress cortisol Chandrasekhar"),
      },
      {
        title: "Ashwagandha and sleep: systematic review and meta-analysis",
        authors: "Cheah et al.",
        journal: "PLOS ONE",
        year: 2021,
        type: "Meta-analysis",
        sample: "5 RCTs · 400 participants",
        dose: "120–600 mg/day",
        duration: "6–12 weeks",
        finding: "Ashwagandha significantly improved overall sleep (SMD 0.59), sleep onset latency, and sleep quality. Effects more pronounced in adults with insomnia.",
        pubmedQuery: pm("ashwagandha sleep meta-analysis Cheah PLOS"),
      },
      {
        title: "Ashwagandha effects on muscle strength and recovery",
        authors: "Wankhede et al.",
        journal: "Journal of the International Society of Sports Nutrition",
        year: 2015,
        type: "RCT",
        sample: "57 young men starting resistance training",
        dose: "600 mg KSM-66/day",
        duration: "8 weeks",
        finding: "Ashwagandha group showed significantly greater strength gains (bench press +46 kg vs +26 kg), muscle size, and post-exercise muscle recovery markers vs placebo.",
        pubmedQuery: pm("ashwagandha strength resistance training Wankhede"),
      },
      {
        title: "Ashwagandha and testosterone in overweight men",
        authors: "Lopresti et al.",
        journal: "American Journal of Men's Health",
        year: 2019,
        type: "RCT",
        sample: "57 overweight men, ages 40–70",
        dose: "300 mg/day Shoden extract",
        duration: "16 weeks",
        finding: "Ashwagandha increased DHEA-S and testosterone by 18% and 14.7% respectively, with significant improvements in self-reported wellbeing and fatigue.",
        pubmedQuery: pm("ashwagandha testosterone overweight Lopresti"),
      },
    ],
  },

  "l-theanine": {
    ingredient: "l-theanine",
    evidenceLevel: "strong",
    summary: "L-theanine is the unique amino acid in tea that promotes alpha brain waves — the 'calm focus' state. It works fast (30–60 minutes) and pairs particularly well with caffeine.",
    bestUseCases: ["Reducing caffeine jitters and anxiety", "Sustained focus during cognitive work", "Pre-stress events (presentations, exams)", "Mild evening relaxation without sedation", "Acute anxiety management"],
    studies: [
      {
        title: "L-theanine and caffeine on cognitive performance and mood",
        authors: "Owen et al.",
        journal: "Nutritional Neuroscience",
        year: 2008,
        type: "RCT",
        sample: "27 healthy adults",
        dose: "97 mg theanine + 40 mg caffeine",
        duration: "Single dose",
        finding: "The combination improved accuracy on attention-switching tasks and reduced susceptibility to distractor stimuli vs caffeine alone — the canonical 'calm focus' finding.",
        pubmedQuery: pm("L-theanine caffeine cognitive performance Owen"),
      },
      {
        title: "L-theanine and stress response",
        authors: "Kimura et al.",
        journal: "Biological Psychology",
        year: 2007,
        type: "RCT",
        sample: "12 healthy adults",
        dose: "200 mg theanine",
        duration: "Single dose, acute stressor",
        finding: "L-theanine reduced heart rate and salivary IgA responses to acute stress, suggesting attenuation of sympathetic nervous system arousal.",
        pubmedQuery: pm("L-theanine stress heart rate Kimura"),
      },
      {
        title: "Anti-stress effects of L-theanine: meta-analysis",
        authors: "Williams et al.",
        journal: "Plant Foods for Human Nutrition",
        year: 2020,
        type: "Systematic Review",
        sample: "9 RCTs",
        dose: "200–400 mg/day",
        duration: "Single dose to 8 weeks",
        finding: "L-theanine significantly reduced acute stress and anxiety in adults exposed to stressors. Chronic supplementation effects were smaller but consistent.",
        pubmedQuery: pm("L-theanine anti-stress meta-analysis Williams"),
      },
      {
        title: "Effects of L-theanine on attention and reaction time",
        authors: "Higashiyama et al.",
        journal: "Journal of Functional Foods",
        year: 2011,
        type: "RCT",
        sample: "18 attention-prone adults",
        dose: "200 mg theanine",
        duration: "Single dose",
        finding: "L-theanine improved reaction time and working memory on cognitive tests in attention-prone adults, without sedation.",
        pubmedQuery: pm("L-theanine attention reaction time Higashiyama"),
      },
    ],
  },

  creatine: {
    ingredient: "creatine",
    evidenceLevel: "very strong",
    summary: "Creatine monohydrate is the most-studied supplement in sports nutrition (500+ trials). Growing evidence shows benefits beyond muscle — cognition, mood, and aging.",
    bestUseCases: ["Strength training performance", "Muscle mass and recovery", "Cognitive performance under sleep deprivation", "Age-related sarcopenia prevention", "Vegan/vegetarian creatine repletion"],
    studies: [
      {
        title: "International Society of Sports Nutrition position stand on creatine",
        authors: "Kreider et al.",
        journal: "Journal of the International Society of Sports Nutrition",
        year: 2017,
        type: "Systematic Review",
        sample: "500+ trials reviewed",
        dose: "3–5 g/day",
        duration: "Maintenance ongoing",
        finding: "ISSN concludes creatine is the most effective ergogenic nutritional supplement available, with substantial benefits for high-intensity exercise and lean mass.",
        pubmedQuery: pm("ISSN creatine position stand Kreider"),
      },
      {
        title: "Creatine supplementation and cognitive performance",
        authors: "Avgerinos et al.",
        journal: "Experimental Gerontology",
        year: 2018,
        type: "Meta-analysis",
        sample: "6 RCTs · 281 participants",
        dose: "5–20 g/day",
        duration: "5 days–6 weeks",
        finding: "Creatine improved short-term memory and intelligence/reasoning, especially in vegetarians and adults experiencing mental fatigue.",
        pubmedQuery: pm("creatine cognitive performance Avgerinos"),
      },
      {
        title: "Creatine supplementation in older adults: muscle mass and function",
        authors: "Forbes et al.",
        journal: "Nutrients",
        year: 2021,
        type: "Meta-analysis",
        sample: "19 RCTs · 609 older adults",
        dose: "3–20 g/day",
        duration: "12+ weeks with resistance training",
        finding: "Creatine + resistance training produced significantly greater gains in lean mass, upper body strength, and lower body strength vs training alone in adults 50+.",
        pubmedQuery: pm("creatine older adults sarcopenia Forbes"),
      },
      {
        title: "Creatine supplementation and depression symptoms",
        authors: "Lyoo et al.",
        journal: "American Journal of Psychiatry",
        year: 2012,
        type: "RCT",
        sample: "52 women with SSRI-resistant depression",
        dose: "5 g/day creatine + SSRI",
        duration: "8 weeks",
        finding: "Adjunctive creatine produced significantly greater improvement in depression scores vs SSRI alone — onset of antidepressant response was also faster.",
        pubmedQuery: pm("creatine depression SSRI Lyoo"),
      },
    ],
  },

  collagen: {
    ingredient: "collagen",
    evidenceLevel: "strong",
    summary: "Hydrolysed collagen peptides survive digestion and reach connective tissue, where they stimulate fibroblast activity. The strongest evidence is for skin and joint outcomes.",
    bestUseCases: ["Skin elasticity and hydration", "Mild osteoarthritis joint comfort", "Athletic recovery (tendons, ligaments)", "Nail strength", "Post-injury connective tissue support"],
    studies: [
      {
        title: "Oral collagen peptides and skin parameters",
        authors: "Choi et al.",
        journal: "Journal of Drugs in Dermatology",
        year: 2019,
        type: "RCT",
        sample: "64 women, ages 40–60",
        dose: "1 g/day collagen peptide",
        duration: "12 weeks",
        finding: "Collagen supplementation significantly improved skin elasticity and hydration vs placebo. Effects were measurable at 4 weeks and continued growing through 12.",
        pubmedQuery: pm("collagen peptide skin elasticity Choi"),
      },
      {
        title: "Collagen hydrolysate and joint pain: systematic review",
        authors: "García-Coronado et al.",
        journal: "International Orthopaedics",
        year: 2019,
        type: "Systematic Review",
        sample: "5 RCTs · ~519 patients",
        dose: "10 g/day",
        duration: "≥6 months",
        finding: "Hydrolysed collagen significantly reduced joint pain in osteoarthritis patients vs placebo. Effect sizes were comparable to glucosamine.",
        pubmedQuery: pm("collagen hydrolysate osteoarthritis García-Coronado"),
      },
      {
        title: "Collagen supplementation in athletes with activity-related joint pain",
        authors: "Clark et al.",
        journal: "Current Medical Research and Opinion",
        year: 2008,
        type: "RCT",
        sample: "147 athletes",
        dose: "10 g/day collagen hydrolysate",
        duration: "24 weeks",
        finding: "Collagen significantly reduced joint pain during activity, at rest, and following exercise vs placebo.",
        pubmedQuery: pm("collagen athletes joint pain Clark"),
      },
      {
        title: "Effects of collagen peptides on nail growth and brittleness",
        authors: "Hexsel et al.",
        journal: "Journal of Cosmetic Dermatology",
        year: 2017,
        type: "Pilot RCT",
        sample: "25 women with brittle nails",
        dose: "2.5 g/day",
        duration: "24 weeks",
        finding: "Collagen produced a 12% increase in nail growth rate, 42% decrease in broken nails, and 64% improvement in clinical symptoms.",
        pubmedQuery: pm("collagen peptide nail brittleness Hexsel"),
      },
    ],
  },

  curcumin: {
    ingredient: "curcumin",
    evidenceLevel: "strong",
    summary: "Curcumin is the active polyphenol in turmeric. Raw curcumin has poor bioavailability — the studied effects rely on enhanced forms (BioPerine, Meriva phytosome, Theracurmin).",
    bestUseCases: ["Knee osteoarthritis pain", "Systemic inflammation reduction", "Mild-to-moderate depression (adjunct)", "Post-exercise muscle soreness", "Metabolic syndrome markers"],
    studies: [
      {
        title: "Curcumin vs NSAIDs in osteoarthritis pain",
        authors: "Daily et al.",
        journal: "Journal of Medicinal Food",
        year: 2016,
        type: "Meta-analysis",
        sample: "8 RCTs · 606 patients",
        dose: "500–1,500 mg/day",
        duration: "4–16 weeks",
        finding: "Curcumin produced pain reductions comparable to ibuprofen and diclofenac in knee osteoarthritis, with significantly fewer adverse events.",
        pubmedQuery: pm("curcumin NSAID osteoarthritis Daily meta-analysis"),
      },
      {
        title: "Curcumin and major depressive disorder",
        authors: "Ng et al.",
        journal: "Journal of Affective Disorders",
        year: 2017,
        type: "Meta-analysis",
        sample: "10 RCTs · 531 patients",
        dose: "500–1,000 mg/day",
        duration: "6+ weeks",
        finding: "Curcumin showed significant antidepressant effects vs placebo (SMD -0.34). The effect was larger in middle-aged adults and as adjunct to antidepressants.",
        pubmedQuery: pm("curcumin depression Ng meta-analysis"),
      },
      {
        title: "Curcumin and inflammatory markers: meta-analysis",
        authors: "Sahebkar et al.",
        journal: "Pharmacological Research",
        year: 2016,
        type: "Meta-analysis",
        sample: "9 RCTs",
        dose: "Variable",
        duration: "Variable",
        finding: "Curcumin significantly reduced circulating IL-6, hs-CRP, and TNF-α — major inflammatory markers — across multiple conditions.",
        pubmedQuery: pm("curcumin inflammation IL-6 CRP Sahebkar"),
      },
    ],
  },

  zinc: {
    ingredient: "zinc",
    evidenceLevel: "very strong",
    summary: "Zinc is essential for over 300 enzymes and is one of the best-evidenced acute-illness supplements. Zinc lozenges (acetate or gluconate) reduce cold duration when started within 24 hours.",
    bestUseCases: ["Acute cold/flu (lozenges at first symptoms)", "Immune cell function support", "Wound healing", "Acne (adjunctive)", "Taste/smell restoration after deficiency"],
    studies: [
      {
        title: "Zinc lozenges and the common cold: meta-analysis",
        authors: "Hemilä",
        journal: "JRSM Open",
        year: 2017,
        type: "Meta-analysis",
        sample: "7 RCTs · 575 participants",
        dose: "≥75 mg/day zinc acetate/gluconate",
        duration: "Acute cold duration",
        finding: "Zinc lozenges at adequate doses reduced cold duration by 33%. Effective forms: zinc acetate and gluconate, ideally started within 24 hours.",
        pubmedQuery: pm("zinc lozenges common cold meta-analysis Hemilä"),
      },
      {
        title: "Zinc supplementation in pneumonia prevention in elderly",
        authors: "Meydani et al.",
        journal: "American Journal of Clinical Nutrition",
        year: 2007,
        type: "RCT",
        sample: "617 nursing home residents",
        dose: "Normal vs low serum zinc",
        duration: "1 year",
        finding: "Adequate zinc status was associated with significantly lower pneumonia incidence and shorter duration of illness.",
        pubmedQuery: pm("zinc pneumonia elderly Meydani"),
      },
      {
        title: "Zinc and male reproductive health",
        authors: "Fallah et al.",
        journal: "Journal of Reproduction & Infertility",
        year: 2018,
        type: "Systematic Review",
        sample: "Multiple human and animal studies",
        dose: "Variable",
        duration: "Variable",
        finding: "Zinc supplementation in zinc-deficient men improved serum testosterone, semen quality, and fertility outcomes.",
        pubmedQuery: pm("zinc male reproductive health Fallah"),
      },
    ],
  },

  "vit-c": {
    ingredient: "vit-c",
    evidenceLevel: "strong",
    summary: "Vitamin C (ascorbic acid) is essential for collagen synthesis, neurotransmitter formation, and antioxidant defense. The well-evidenced uses are around cold duration and exercise stress.",
    bestUseCases: ["Cold duration reduction (especially in active people)", "Iron absorption enhancement", "Daily antioxidant support", "Wound healing", "Collagen synthesis pairing"],
    studies: [
      {
        title: "Vitamin C for preventing and treating the common cold",
        authors: "Hemilä & Chalker",
        journal: "Cochrane Database of Systematic Reviews",
        year: 2013,
        type: "Meta-analysis",
        sample: "29 RCTs · 11,306 participants",
        dose: "≥200 mg/day",
        duration: "Ongoing",
        finding: "Regular vitamin C didn't reduce cold incidence in the general population, but reduced cold duration by 8% in adults and 14% in children. Larger benefit in athletes (52% reduction in incidence).",
        pubmedQuery: pm("vitamin C common cold Hemilä Cochrane"),
      },
      {
        title: "Vitamin C and exercise-induced oxidative stress",
        authors: "Braakhuis & Hopkins",
        journal: "Sports Medicine",
        year: 2015,
        type: "Systematic Review",
        sample: "Multiple RCTs reviewed",
        dose: "200–1,000 mg/day",
        duration: "Variable",
        finding: "Moderate vitamin C (200–500 mg) supports recovery in athletes. Mega-doses (>1 g) may blunt training adaptations — moderation matters.",
        pubmedQuery: pm("vitamin C exercise oxidative Braakhuis"),
      },
      {
        title: "Vitamin C and iron absorption",
        authors: "Cook & Reddy",
        journal: "American Journal of Clinical Nutrition",
        year: 2001,
        type: "RCT",
        sample: "Crossover study, healthy adults",
        dose: "100 mg vitamin C with iron",
        duration: "Per meal",
        finding: "Vitamin C taken with iron-rich meals dramatically enhances non-heme iron absorption — clinically meaningful for vegetarians and women with low ferritin.",
        pubmedQuery: pm("vitamin C iron absorption Cook Reddy"),
      },
    ],
  },

  probiotic: {
    ingredient: "probiotic",
    evidenceLevel: "strong",
    summary: "Probiotic effects are strain-specific. Generic 'probiotic' doesn't mean much — the evidence accumulates around specific strains tested for specific conditions.",
    bestUseCases: ["Antibiotic-associated diarrhea prevention (S. boulardii, LGG)", "IBS symptoms (B. infantis 35624)", "Acute infectious diarrhea (LGG)", "Mood and anxiety (Lactobacillus helveticus + B. longum)", "Vaginal microbiome (L. crispatus)"],
    studies: [
      {
        title: "Probiotics for prevention of antibiotic-associated diarrhea",
        authors: "Goldenberg et al.",
        journal: "Cochrane Database of Systematic Reviews",
        year: 2017,
        type: "Meta-analysis",
        sample: "33 RCTs · 6,352 children/adults",
        dose: "Various strains",
        duration: "During + 2 weeks post-antibiotics",
        finding: "Probiotic supplementation reduced antibiotic-associated diarrhea risk by 60% (RR 0.40). Strongest evidence: Lactobacillus rhamnosus GG and Saccharomyces boulardii.",
        pubmedQuery: pm("probiotics antibiotic associated diarrhea Goldenberg Cochrane"),
      },
      {
        title: "Probiotics in irritable bowel syndrome",
        authors: "Ford et al.",
        journal: "American Journal of Gastroenterology",
        year: 2018,
        type: "Meta-analysis",
        sample: "53 RCTs · 5,545 patients",
        dose: "Various",
        duration: "≥4 weeks",
        finding: "Probiotics significantly improved global IBS symptoms vs placebo (RR 0.79). Bifidobacterium infantis 35624 had the strongest single-strain evidence.",
        pubmedQuery: pm("probiotics IBS Ford American Journal Gastroenterology"),
      },
      {
        title: "Probiotic effects on depression and anxiety",
        authors: "Liu et al.",
        journal: "Neuroscience & Biobehavioral Reviews",
        year: 2019,
        type: "Meta-analysis",
        sample: "34 RCTs · 2,165 participants",
        dose: "Various multi-strain",
        duration: "≥4 weeks",
        finding: "Probiotic supplementation produced small but significant improvements in depression and anxiety scores (SMD -0.13 and -0.31).",
        pubmedQuery: pm("probiotic depression anxiety Liu meta-analysis"),
      },
    ],
  },

  rhodiola: {
    ingredient: "rhodiola",
    evidenceLevel: "moderate",
    summary: "Rhodiola rosea is the most-studied energising adaptogen. Standardized extracts (3% rosavins, 1% salidrosides) show consistent effects on mental fatigue and stress endurance.",
    bestUseCases: ["Mental fatigue and burnout", "Stress-induced low mood", "Endurance performance under fatigue", "Exam/work performance under pressure", "Mild depressive symptoms"],
    studies: [
      {
        title: "Rhodiola rosea for mental fatigue in physicians",
        authors: "Darbinyan et al.",
        journal: "Phytomedicine",
        year: 2000,
        type: "RCT",
        sample: "56 physicians on night duty",
        dose: "170 mg/day standardized extract",
        duration: "2 weeks",
        finding: "Rhodiola significantly reduced mental fatigue and improved cognitive performance vs placebo in stressed working adults.",
        pubmedQuery: pm("rhodiola rosea mental fatigue physicians Darbinyan"),
      },
      {
        title: "Rhodiola rosea in chronic stress: systematic review",
        authors: "Anghelescu et al.",
        journal: "International Journal of Psychiatry in Clinical Practice",
        year: 2018,
        type: "Systematic Review",
        sample: "11 RCTs",
        dose: "200–680 mg/day",
        duration: "4–12 weeks",
        finding: "Rhodiola consistently reduced symptoms of stress, fatigue, and exhaustion across trials, with a favourable safety profile.",
        pubmedQuery: pm("rhodiola rosea chronic stress systematic review Anghelescu"),
      },
      {
        title: "Rhodiola in mild-to-moderate depression",
        authors: "Mao et al.",
        journal: "Phytomedicine",
        year: 2015,
        type: "RCT",
        sample: "57 adults with mild-to-moderate depression",
        dose: "340–680 mg/day",
        duration: "12 weeks",
        finding: "Rhodiola produced clinically meaningful antidepressant effects, smaller than sertraline but with significantly fewer side effects.",
        pubmedQuery: pm("rhodiola depression sertraline Mao"),
      },
    ],
  },

  "lions-mane": {
    ingredient: "lions-mane",
    evidenceLevel: "moderate",
    summary: "Lion's mane (Hericium erinaceus) contains hericenones and erinacines — compounds that stimulate nerve growth factor (NGF). Human evidence is most established for mild cognitive decline.",
    bestUseCases: ["Mild cognitive decline / early memory issues", "Mood support (early evidence)", "Nerve regeneration (mechanistic)", "Stress-related cognitive performance"],
    studies: [
      {
        title: "Lion's mane mushroom and mild cognitive impairment",
        authors: "Mori et al.",
        journal: "Phytotherapy Research",
        year: 2009,
        type: "RCT",
        sample: "30 older adults with MCI",
        dose: "1 g lion's mane extract 3×/day",
        duration: "16 weeks",
        finding: "Lion's mane significantly improved cognitive function scores vs placebo. Benefits diminished after discontinuation, suggesting active mechanism rather than disease modification.",
        pubmedQuery: pm("lion's mane Hericium cognitive impairment Mori"),
      },
      {
        title: "Hericium erinaceus and depressive/anxious mood",
        authors: "Nagano et al.",
        journal: "Biomedical Research",
        year: 2010,
        type: "RCT",
        sample: "30 menopausal women",
        dose: "Cookies containing lion's mane",
        duration: "4 weeks",
        finding: "Lion's mane consumption produced significant reductions in depression, anxiety, and irritability scores vs placebo cookies.",
        pubmedQuery: pm("Hericium erinaceus depression menopausal Nagano"),
      },
      {
        title: "Lion's mane and nerve growth factor activity",
        authors: "Lai et al.",
        journal: "International Journal of Medicinal Mushrooms",
        year: 2013,
        type: "Mechanistic",
        sample: "In vitro and animal models",
        dose: "Variable",
        duration: "Variable",
        finding: "Hericenones and erinacines from lion's mane cross the blood-brain barrier and stimulate NGF synthesis, providing a plausible mechanism for cognitive benefits.",
        pubmedQuery: pm("Hericium erinaceus NGF nerve growth factor Lai"),
      },
    ],
  },

  coq10: {
    ingredient: "coq10",
    evidenceLevel: "strong",
    summary: "CoQ10 (and its reduced form ubiquinol) is essential for mitochondrial ATP production. Levels decline with age and are depleted by statins. Strongest evidence: heart failure, statin-associated muscle pain, migraine prevention.",
    bestUseCases: ["Statin-associated muscle symptoms", "Heart failure (adjunct)", "Migraine prevention", "Age-related fatigue", "Fertility support (egg quality)"],
    studies: [
      {
        title: "Coenzyme Q10 in heart failure: Q-SYMBIO",
        authors: "Mortensen et al.",
        journal: "JACC: Heart Failure",
        year: 2014,
        type: "RCT",
        sample: "420 patients with moderate-severe heart failure",
        dose: "100 mg CoQ10 3×/day",
        duration: "2 years",
        finding: "CoQ10 reduced major adverse cardiovascular events by 43% and all-cause mortality by 42% vs placebo in patients with chronic heart failure.",
        pubmedQuery: pm("Q-SYMBIO CoQ10 heart failure Mortensen"),
      },
      {
        title: "CoQ10 for statin-associated muscle symptoms",
        authors: "Qu et al.",
        journal: "Atherosclerosis",
        year: 2018,
        type: "Meta-analysis",
        sample: "12 RCTs · 575 patients",
        dose: "100–600 mg/day",
        duration: "Variable",
        finding: "CoQ10 supplementation produced significant reductions in statin-associated muscle pain, weakness, cramps, and tiredness vs placebo.",
        pubmedQuery: pm("CoQ10 statin myalgia Qu meta-analysis"),
      },
      {
        title: "CoQ10 and migraine prevention",
        authors: "Sándor et al.",
        journal: "Neurology",
        year: 2005,
        type: "RCT",
        sample: "42 migraineurs",
        dose: "100 mg CoQ10 3×/day",
        duration: "3 months",
        finding: "CoQ10 reduced migraine frequency by 50%+ in significantly more patients than placebo (47% vs 14%).",
        pubmedQuery: pm("CoQ10 migraine prevention Sándor Neurology"),
      },
    ],
  },

  nac: {
    ingredient: "nac",
    evidenceLevel: "strong",
    summary: "N-acetyl cysteine (NAC) is the rate-limiting precursor to glutathione, the body's master antioxidant. Well-evidenced for respiratory mucus, OCD/trichotillomania, and acetaminophen toxicity (clinical IV use).",
    bestUseCases: ["Productive cough / mucus thinning", "Trichotillomania, skin-picking, OCD-spectrum disorders", "Liver support / acetaminophen recovery", "PCOS adjunct", "Fertility (male sperm quality)"],
    studies: [
      {
        title: "NAC for chronic bronchitis",
        authors: "Stey et al.",
        journal: "European Respiratory Journal",
        year: 2000,
        type: "Meta-analysis",
        sample: "11 RCTs · 2,011 patients",
        dose: "400–600 mg/day",
        duration: "≥3 months",
        finding: "NAC significantly reduced acute exacerbations of chronic bronchitis (relative risk reduction 23%) and improved symptoms.",
        pubmedQuery: pm("N-acetyl cysteine chronic bronchitis Stey meta-analysis"),
      },
      {
        title: "NAC in obsessive-compulsive and related disorders",
        authors: "Grant et al.",
        journal: "Archives of General Psychiatry",
        year: 2009,
        type: "RCT",
        sample: "50 trichotillomania patients",
        dose: "1,200–2,400 mg/day",
        duration: "12 weeks",
        finding: "NAC produced significant reductions in hair-pulling symptoms vs placebo, with 56% of NAC patients showing 'much improved' status.",
        pubmedQuery: pm("NAC trichotillomania Grant Archives Psychiatry"),
      },
      {
        title: "NAC and male fertility: meta-analysis",
        authors: "Jannatifar et al.",
        journal: "Reproductive Biology and Endocrinology",
        year: 2019,
        type: "Meta-analysis",
        sample: "9 RCTs",
        dose: "600 mg/day",
        duration: "≥3 months",
        finding: "NAC supplementation significantly improved sperm count, motility, and morphology in infertile men with oxidative stress markers.",
        pubmedQuery: pm("NAC male fertility sperm Jannatifar"),
      },
    ],
  },

  b12: {
    ingredient: "b12",
    evidenceLevel: "very strong",
    summary: "Vitamin B12 (cobalamin) deficiency is one of the most common nutrient deficiencies globally, especially in vegans, vegetarians, and adults over 50 (absorption drops with age).",
    bestUseCases: ["Vegan/vegetarian supplementation", "Adults 50+ (declining absorption)", "Pernicious anaemia management", "Metformin-induced B12 depletion", "Brain fog / fatigue with low B12 status"],
    studies: [
      {
        title: "Vitamin B12 deficiency prevalence in vegetarians and vegans",
        authors: "Pawlak et al.",
        journal: "Nutrition Reviews",
        year: 2013,
        type: "Systematic Review",
        sample: "40 studies pooled",
        dose: "—",
        duration: "—",
        finding: "B12 deficiency prevalence: 62% in pregnant vegetarians, 25–86% in children, 21–41% in adolescents, 11–90% in elderly. Supplementation effectively reverses status.",
        pubmedQuery: pm("vitamin B12 deficiency vegetarians vegans Pawlak"),
      },
      {
        title: "Metformin-induced vitamin B12 deficiency",
        authors: "Aroda et al.",
        journal: "Journal of Clinical Endocrinology & Metabolism",
        year: 2016,
        type: "Cohort",
        sample: "Diabetes Prevention Program participants",
        dose: "—",
        duration: "Long-term metformin use",
        finding: "Long-term metformin use significantly increased B12 deficiency risk (OR 2.92). Annual B12 testing recommended for chronic metformin users.",
        pubmedQuery: pm("metformin B12 deficiency Aroda"),
      },
      {
        title: "Oral vs intramuscular B12 for deficiency correction",
        authors: "Vidal-Alaball et al.",
        journal: "Cochrane Database of Systematic Reviews",
        year: 2005,
        type: "Systematic Review",
        sample: "Multiple RCTs",
        dose: "1,000–2,000 mcg/day oral",
        duration: "≥4 weeks",
        finding: "Oral B12 at adequate doses is as effective as intramuscular injection for correcting deficiency in most patients without absorption issues.",
        pubmedQuery: pm("oral intramuscular B12 deficiency Vidal-Alaball"),
      },
    ],
  },

  iron: {
    ingredient: "iron",
    evidenceLevel: "very strong",
    summary: "Iron deficiency (with or without anaemia) is the world's most common nutrient deficiency, especially in menstruating women and athletes. Supplementation should follow ferritin testing.",
    bestUseCases: ["Confirmed low ferritin (test first!)", "Heavy menstrual bleeding", "Endurance athletes", "Pregnancy", "Restless legs from low iron"],
    studies: [
      {
        title: "Iron supplementation in iron-deficient non-anaemic women",
        authors: "Verdon et al.",
        journal: "BMJ",
        year: 2003,
        type: "RCT",
        sample: "144 women with unexplained fatigue + low ferritin",
        dose: "80 mg/day ferrous sulfate",
        duration: "4 weeks",
        finding: "Iron significantly reduced fatigue scores in non-anaemic women with low ferritin (≤50 ng/mL) — the first trial supporting low-ferritin treatment without anaemia.",
        pubmedQuery: pm("iron fatigue non-anaemic women Verdon BMJ"),
      },
      {
        title: "Alternate-day iron supplementation improves absorption",
        authors: "Stoffel et al.",
        journal: "The Lancet Haematology",
        year: 2017,
        type: "RCT",
        sample: "40 iron-deficient women",
        dose: "60–120 mg ferrous sulfate",
        duration: "—",
        finding: "Alternate-day dosing (rather than daily) significantly improved iron absorption and reduced GI side effects. This changed clinical practice globally.",
        pubmedQuery: pm("iron alternate day Stoffel Lancet"),
      },
      {
        title: "Iron and restless legs syndrome",
        authors: "Allen et al.",
        journal: "Sleep Medicine",
        year: 2018,
        type: "Systematic Review",
        sample: "Pooled clinical evidence",
        dose: "65 mg/day with vitamin C",
        duration: "12+ weeks",
        finding: "Iron supplementation significantly reduced restless legs severity in patients with serum ferritin <75 ng/mL.",
        pubmedQuery: pm("iron restless legs Allen Sleep Medicine"),
      },
    ],
  },

  melatonin: {
    ingredient: "melatonin",
    evidenceLevel: "strong",
    summary: "Melatonin is a signalling hormone (not a sedative). Best evidence is for jet lag, shift work, and circadian rhythm disorders. Most adults benefit from much lower doses than typically sold.",
    bestUseCases: ["Jet lag (eastward travel)", "Shift work circadian adjustment", "Delayed sleep phase disorder", "Mild age-related insomnia", "Pre-procedure anxiety (clinical)"],
    studies: [
      {
        title: "Melatonin for jet lag prevention",
        authors: "Herxheimer & Petrie",
        journal: "Cochrane Database of Systematic Reviews",
        year: 2002,
        type: "Meta-analysis",
        sample: "10 RCTs",
        dose: "0.5–5 mg at destination bedtime",
        duration: "—",
        finding: "Melatonin was highly effective for jet lag from eastward travel across 5+ time zones. Doses 0.5–5 mg performed similarly — lower doses sufficient.",
        pubmedQuery: pm("melatonin jet lag Herxheimer Cochrane"),
      },
      {
        title: "Low-dose vs high-dose melatonin for insomnia in older adults",
        authors: "Wade et al.",
        journal: "Current Medical Research and Opinion",
        year: 2007,
        type: "RCT",
        sample: "354 older adults with insomnia",
        dose: "0.3 mg vs 5 mg",
        duration: "3 weeks",
        finding: "Low-dose (0.3 mg) melatonin matched physiological levels and improved sleep without next-day grogginess. Higher doses (5 mg) caused next-day fatigue.",
        pubmedQuery: pm("melatonin low dose insomnia elderly Wade"),
      },
      {
        title: "Melatonin and delayed sleep phase disorder",
        authors: "Sletten et al.",
        journal: "PLOS Medicine",
        year: 2018,
        type: "RCT",
        sample: "116 adults with delayed sleep phase",
        dose: "0.5 mg taken 1 hr before desired sleep",
        duration: "4 weeks",
        finding: "Low-dose melatonin successfully advanced sleep timing and improved sleep onset latency by ~34 minutes in delayed sleep phase disorder.",
        pubmedQuery: pm("melatonin delayed sleep phase disorder Sletten"),
      },
    ],
  },

  "5-htp": {
    ingredient: "5-htp",
    evidenceLevel: "moderate",
    summary: "5-HTP is the direct precursor to serotonin. Effects are real but should not be combined with SSRIs/MAOIs. Evidence is most established for mild depression and fibromyalgia.",
    bestUseCases: ["Mild low mood (when not on SSRIs)", "Fibromyalgia pain and sleep", "Sleep onset issues from low serotonin", "Cluster headache (some evidence)"],
    studies: [
      {
        title: "5-HTP in depression: meta-analysis",
        authors: "Shaw et al.",
        journal: "Cochrane Database of Systematic Reviews",
        year: 2002,
        type: "Meta-analysis",
        sample: "Pooled RCTs",
        dose: "200–300 mg/day",
        duration: "2+ weeks",
        finding: "5-HTP showed antidepressant effects in pooled studies, though methodological quality was variable. Effects similar to tricyclic antidepressants in older trials.",
        pubmedQuery: pm("5-HTP depression Shaw Cochrane"),
      },
      {
        title: "5-HTP and fibromyalgia",
        authors: "Caruso et al.",
        journal: "Journal of International Medical Research",
        year: 1990,
        type: "RCT",
        sample: "50 fibromyalgia patients",
        dose: "100 mg 3×/day",
        duration: "30 days",
        finding: "5-HTP produced significant improvements in tender points, pain intensity, morning stiffness, sleep, and anxiety vs placebo.",
        pubmedQuery: pm("5-HTP fibromyalgia Caruso"),
      },
    ],
  },

  nmn: {
    ingredient: "nmn",
    evidenceLevel: "emerging",
    summary: "NMN is one of the most active research areas in longevity science. Multiple recent human trials confirm safe NAD+ elevation. Functional outcomes are still being characterised — promising but not yet definitive.",
    bestUseCases: ["Restoring age-related NAD+ decline", "Energy and endurance in adults 40+", "Insulin sensitivity (early evidence)", "Longevity protocols (Sinclair group)"],
    studies: [
      {
        title: "Chronic NMN supplementation and insulin sensitivity",
        authors: "Yoshino et al.",
        journal: "Science",
        year: 2021,
        type: "RCT",
        sample: "25 postmenopausal women with prediabetes",
        dose: "250 mg/day NMN",
        duration: "10 weeks",
        finding: "NMN significantly improved muscle insulin sensitivity, muscle remodeling signaling, and aerobic capacity vs placebo.",
        pubmedQuery: pm("NMN nicotinamide mononucleotide insulin Yoshino Science"),
      },
      {
        title: "NMN and aerobic capacity / functional performance",
        authors: "Liao et al.",
        journal: "Journal of the International Society of Sports Nutrition",
        year: 2021,
        type: "RCT",
        sample: "48 amateur runners",
        dose: "300–1,200 mg/day NMN",
        duration: "6 weeks",
        finding: "NMN dose-dependently improved aerobic capacity (VO2 max) and ventilatory threshold in runners — first evidence of performance benefit in healthy adults.",
        pubmedQuery: pm("NMN aerobic capacity runners Liao"),
      },
      {
        title: "Safety and NAD+ elevation in healthy older adults",
        authors: "Igarashi et al.",
        journal: "npj Aging",
        year: 2022,
        type: "RCT",
        sample: "108 older adults",
        dose: "250 mg/day NMN",
        duration: "12 weeks",
        finding: "NMN safely elevated blood NAD+ levels by ~38% and improved walking endurance and right-leg muscle function in adults 60+.",
        pubmedQuery: pm("NMN NAD older adults Igarashi npj Aging"),
      },
    ],
  },

  nr: {
    ingredient: "nr",
    evidenceLevel: "strong",
    summary: "NR (Nicotinamide Riboside) is the most clinically-studied NAD+ precursor. The NIAGEN form has 20+ published human trials confirming safe NAD+ elevation.",
    bestUseCases: ["Restoring age-related NAD+ decline", "Mitochondrial energy support", "Adults 40+ longevity protocols", "Recovery from physical stress"],
    studies: [
      {
        title: "Chronic NR supplementation and NAD+ metabolome",
        authors: "Trammell et al.",
        journal: "Nature Communications",
        year: 2016,
        type: "RCT",
        sample: "12 healthy adults",
        dose: "Single doses up to 1,000 mg NR",
        duration: "Acute and chronic",
        finding: "NR safely and dose-dependently increased blood NAD+ levels in humans — first definitive proof of human bioavailability of an NAD+ precursor.",
        pubmedQuery: pm("NR nicotinamide riboside NAD Trammell Nature"),
      },
      {
        title: "NR and cardiovascular function in older adults",
        authors: "Martens et al.",
        journal: "Nature Communications",
        year: 2018,
        type: "RCT",
        sample: "24 healthy older adults",
        dose: "500 mg NR 2×/day",
        duration: "6 weeks",
        finding: "NR safely elevated NAD+ and reduced systolic blood pressure and arterial stiffness in adults at risk for cardiovascular disease.",
        pubmedQuery: pm("nicotinamide riboside arterial stiffness Martens"),
      },
      {
        title: "NR safety and tolerability: pooled analysis",
        authors: "Conze et al.",
        journal: "Nutrients",
        year: 2019,
        type: "Systematic Review",
        sample: "8 clinical trials",
        dose: "100–2,000 mg/day",
        duration: "1 day–12 weeks",
        finding: "NIAGEN (the patented NR form) demonstrated a clean safety profile across trials, with no serious adverse events attributable to supplementation.",
        pubmedQuery: pm("nicotinamide riboside safety Conze Nutrients"),
      },
    ],
  },

  "urolithin-a": {
    ingredient: "urolithin-a",
    evidenceLevel: "strong",
    summary: "Urolithin A is one of the most rigorously researched longevity ingredients of the last decade. The Mitopure form is the only commercially-available source with published RCTs.",
    bestUseCases: ["Mitophagy support in adults 40+", "Muscle endurance preservation", "Older adults with declining physical function", "Recovery in active populations"],
    studies: [
      {
        title: "Urolithin A and mitochondrial health in humans",
        authors: "Andreux et al.",
        journal: "Nature Metabolism",
        year: 2019,
        type: "RCT",
        sample: "60 sedentary older adults",
        dose: "250–1,000 mg/day",
        duration: "4 weeks",
        finding: "Urolithin A dose-dependently improved mitochondrial gene expression and muscle function biomarkers — first human evidence of mitophagy induction by an oral supplement.",
        pubmedQuery: pm("urolithin A Mitopure mitochondrial Andreux Nature"),
      },
      {
        title: "Urolithin A and muscle endurance in middle-aged adults",
        authors: "Singh et al.",
        journal: "Cell Reports Medicine",
        year: 2022,
        type: "RCT",
        sample: "88 middle-aged adults",
        dose: "500–1,000 mg/day Mitopure",
        duration: "16 weeks",
        finding: "Urolithin A significantly improved muscle endurance (hand grip, leg muscle) and reduced inflammatory markers vs placebo in middle-aged adults.",
        pubmedQuery: pm("urolithin A muscle endurance Singh Cell Reports"),
      },
      {
        title: "Urolithin A safety and biomarker effects",
        authors: "Liu et al.",
        journal: "JAMA Network Open",
        year: 2022,
        type: "RCT",
        sample: "66 older adults",
        dose: "500 mg/day",
        duration: "4 months",
        finding: "Urolithin A demonstrated favourable safety, improved muscle strength (~12% vs placebo), and significantly increased peak power output during exercise tests.",
        pubmedQuery: pm("urolithin A safety older adults Liu JAMA"),
      },
    ],
  },

  fisetin: {
    ingredient: "fisetin",
    evidenceLevel: "emerging",
    summary: "Fisetin is one of the leading senolytic candidates — compounds that selectively clear senescent ('zombie') cells that accumulate with age. Mayo Clinic has multiple ongoing trials.",
    bestUseCases: ["Senolytic protocols (intermittent 2-day pulses)", "Anti-inflammatory support", "Longevity stacks", "Age-related cellular health"],
    studies: [
      {
        title: "Fisetin as a senotherapeutic: preclinical evidence",
        authors: "Yousefzadeh et al.",
        journal: "EBioMedicine",
        year: 2018,
        type: "Mechanistic",
        sample: "Aged mice and human cell lines",
        dose: "100 mg/kg (mouse equivalent)",
        duration: "Acute and chronic",
        finding: "Fisetin reduced senescent cell burden in multiple tissues, extended median and maximum lifespan in mice (12% increase), and reduced age-related pathology.",
        pubmedQuery: pm("fisetin senolytic senescent cells Yousefzadeh"),
      },
      {
        title: "Fisetin trial in frailty: AFFIRM-LITE",
        authors: "Mayo Clinic group (Kirkland et al.)",
        journal: "ClinicalTrials.gov (NCT03675724)",
        year: 2024,
        type: "RCT",
        sample: "Active recruitment",
        dose: "20 mg/kg",
        duration: "2 consecutive days",
        finding: "Active human trials at Mayo Clinic investigating fisetin's effects on frailty, function, and senescence markers in older adults. Results expected to clarify clinical role.",
        pubmedQuery: pm("fisetin AFFIRM frailty Mayo Clinic"),
      },
    ],
  },

  "tart-cherry": {
    ingredient: "tart-cherry",
    evidenceLevel: "strong",
    summary: "Montmorency tart cherry concentrates anthocyanins and natural melatonin precursors. Well-evidenced for sleep, muscle soreness, and uric acid reduction.",
    bestUseCases: ["Post-exercise muscle soreness reduction", "Sleep onset and duration", "Mild gout / uric acid management", "Marathon and endurance recovery"],
    studies: [
      {
        title: "Tart cherry juice and sleep quality",
        authors: "Howatson et al.",
        journal: "European Journal of Nutrition",
        year: 2012,
        type: "RCT",
        sample: "20 healthy adults",
        dose: "30 ml concentrate 2×/day",
        duration: "7 days",
        finding: "Tart cherry significantly elevated nighttime melatonin and improved sleep duration, efficiency, and onset latency vs placebo.",
        pubmedQuery: pm("tart cherry sleep Howatson European Journal Nutrition"),
      },
      {
        title: "Tart cherry and post-marathon recovery",
        authors: "Howatson et al.",
        journal: "Scandinavian Journal of Medicine & Science in Sports",
        year: 2010,
        type: "RCT",
        sample: "20 marathon runners",
        dose: "Tart cherry juice 5 days pre-race",
        duration: "Race + 48 hours",
        finding: "Tart cherry significantly preserved muscle function, reduced inflammatory markers (IL-6, CRP), and reduced post-race oxidative stress vs placebo.",
        pubmedQuery: pm("tart cherry marathon recovery Howatson"),
      },
      {
        title: "Tart cherry and uric acid",
        authors: "Bell et al.",
        journal: "Journal of Functional Foods",
        year: 2014,
        type: "RCT",
        sample: "12 healthy adults",
        dose: "30 ml concentrate",
        duration: "Acute response",
        finding: "Tart cherry consumption significantly reduced serum uric acid and increased urinary uric acid excretion within hours — relevant for gout management.",
        pubmedQuery: pm("tart cherry uric acid gout Bell"),
      },
    ],
  },

  hmb: {
    ingredient: "hmb",
    evidenceLevel: "strong",
    summary: "β-hydroxy β-methylbutyrate is the leucine metabolite that signals muscle preservation. Most effective in catabolic states — older adults, illness, bed rest, calorie deficit.",
    bestUseCases: ["Older adults preventing sarcopenia", "Calorie deficit / cutting phases", "Recovery from immobilization or illness", "Beginner trainees", "Reducing exercise-induced muscle damage"],
    studies: [
      {
        title: "HMB and muscle in older adults: meta-analysis",
        authors: "Wu et al.",
        journal: "Archives of Gerontology and Geriatrics",
        year: 2015,
        type: "Meta-analysis",
        sample: "7 RCTs · 287 older adults",
        dose: "3 g/day",
        duration: "8 weeks–1 year",
        finding: "HMB significantly preserved lean body mass in older adults, with the largest effects in those with sarcopenia or undergoing periods of inactivity.",
        pubmedQuery: pm("HMB older adults muscle mass Wu meta-analysis"),
      },
      {
        title: "HMB during bed rest in elderly",
        authors: "Deutz et al.",
        journal: "Clinical Nutrition",
        year: 2013,
        type: "RCT",
        sample: "24 healthy older adults",
        dose: "3 g/day HMB",
        duration: "10 days bed rest + recovery",
        finding: "HMB completely prevented the loss of lean leg mass during 10 days of bed rest, while placebo group lost significant muscle. Striking effect in catabolic state.",
        pubmedQuery: pm("HMB bed rest elderly Deutz"),
      },
      {
        title: "HMB and resistance exercise: ISSN position",
        authors: "Wilson et al.",
        journal: "Journal of the International Society of Sports Nutrition",
        year: 2013,
        type: "Systematic Review",
        sample: "Multiple RCTs reviewed",
        dose: "3 g/day",
        duration: "Variable",
        finding: "HMB enhanced training adaptations in untrained and elderly populations. Smaller effects in well-trained athletes, but useful during high-volume phases.",
        pubmedQuery: pm("HMB ISSN position stand Wilson resistance training"),
      },
    ],
  },

  berberine: {
    ingredient: "berberine",
    evidenceLevel: "strong",
    summary: "Berberine is a plant alkaloid with effects comparable to metformin on insulin sensitivity. Strong evidence for diabetes, PCOS, and lipid profile, though GI tolerability varies.",
    bestUseCases: ["Type 2 diabetes glucose control", "PCOS insulin resistance", "Mild-to-moderate hypercholesterolemia", "Metabolic syndrome", "Visceral fat reduction"],
    studies: [
      {
        title: "Berberine vs metformin in type 2 diabetes",
        authors: "Yin et al.",
        journal: "Metabolism",
        year: 2008,
        type: "RCT",
        sample: "36 newly diagnosed diabetics",
        dose: "500 mg 3×/day",
        duration: "3 months",
        finding: "Berberine reduced HbA1c, fasting glucose, and lipid markers comparably to metformin (500 mg 3×/day). Both were similarly effective.",
        pubmedQuery: pm("berberine metformin type 2 diabetes Yin Metabolism"),
      },
      {
        title: "Berberine in PCOS: meta-analysis",
        authors: "Li et al.",
        journal: "European Journal of Endocrinology",
        year: 2019,
        type: "Meta-analysis",
        sample: "9 RCTs",
        dose: "1,500 mg/day",
        duration: "3+ months",
        finding: "Berberine improved insulin resistance, androgen levels, and menstrual regularity in PCOS comparably to metformin, with better GI tolerability in some patients.",
        pubmedQuery: pm("berberine PCOS Li meta-analysis"),
      },
      {
        title: "Berberine and serum lipids: meta-analysis",
        authors: "Dong et al.",
        journal: "Phytomedicine",
        year: 2013,
        type: "Meta-analysis",
        sample: "11 RCTs · 874 patients",
        dose: "0.5–1.5 g/day",
        duration: "2+ months",
        finding: "Berberine significantly reduced total cholesterol (–24 mg/dL), LDL (–25 mg/dL), and triglycerides (–44 mg/dL) vs placebo — effects comparable to mild statin doses.",
        pubmedQuery: pm("berberine lipids cholesterol Dong meta-analysis"),
      },
    ],
  },

  saffron: {
    ingredient: "saffron",
    evidenceLevel: "strong",
    summary: "Saffron extract — particularly the standardized Affron form — has emerged as one of the better-evidenced botanical antidepressants. Effects are comparable to SSRIs in mild-to-moderate depression.",
    bestUseCases: ["Mild-to-moderate depression", "Premenstrual dysphoric disorder (PMDD)", "Mild anxiety with low mood", "Sexual side effects from SSRIs (adjunct)"],
    studies: [
      {
        title: "Saffron vs SSRIs in major depressive disorder",
        authors: "Hausenblas et al.",
        journal: "Journal of Integrative Medicine",
        year: 2015,
        type: "Meta-analysis",
        sample: "12 RCTs · 712 patients",
        dose: "30 mg/day",
        duration: "6–8 weeks",
        finding: "Saffron extract was significantly more effective than placebo and as effective as fluoxetine or citalopram in mild-to-moderate depression.",
        pubmedQuery: pm("saffron depression meta-analysis Hausenblas"),
      },
      {
        title: "Saffron in premenstrual syndrome",
        authors: "Agha-Hosseini et al.",
        journal: "BJOG",
        year: 2008,
        type: "RCT",
        sample: "50 women with PMS",
        dose: "30 mg/day saffron extract",
        duration: "2 menstrual cycles",
        finding: "Saffron significantly reduced PMS symptom severity and depression compared with placebo in 76% vs 8% of participants.",
        pubmedQuery: pm("saffron PMS premenstrual syndrome Agha-Hosseini"),
      },
    ],
  },

  bacopa: {
    ingredient: "bacopa",
    evidenceLevel: "strong",
    summary: "Bacopa monnieri is one of the most-studied nootropic botanicals. Effects are slow-onset (8–12 weeks) but consistent for memory, learning, and information processing.",
    bestUseCases: ["Memory and learning enhancement", "Older adults with mild cognitive complaints", "Students and knowledge workers (long-term use)", "Mild anxiety"],
    studies: [
      {
        title: "Bacopa monnieri and cognitive performance: meta-analysis",
        authors: "Kongkeaw et al.",
        journal: "Journal of Ethnopharmacology",
        year: 2014,
        type: "Meta-analysis",
        sample: "9 RCTs · 437 participants",
        dose: "300–450 mg/day standardized",
        duration: "8–12 weeks",
        finding: "Bacopa significantly improved cognitive performance, particularly attention, working memory, and information processing speed.",
        pubmedQuery: pm("bacopa monnieri cognitive Kongkeaw meta-analysis"),
      },
      {
        title: "Bacopa effects on memory in older adults",
        authors: "Calabrese et al.",
        journal: "Journal of Alternative and Complementary Medicine",
        year: 2008,
        type: "RCT",
        sample: "48 adults aged 65+",
        dose: "300 mg/day standardized",
        duration: "12 weeks",
        finding: "Bacopa significantly improved memory recall, anxiety, and depression scores in cognitively healthy older adults vs placebo.",
        pubmedQuery: pm("bacopa memory older adults Calabrese"),
      },
    ],
  },

  "acetyl-l-carnitine": {
    ingredient: "acetyl-l-carnitine",
    evidenceLevel: "strong",
    summary: "Acetyl-L-carnitine (ALCAR) is a mitochondrial carrier compound that crosses the blood-brain barrier. Strongest evidence is for diabetic neuropathy, age-related cognitive decline, and mental fatigue.",
    bestUseCases: ["Diabetic peripheral neuropathy", "Age-related mental fatigue", "Mild cognitive impairment", "Depression in older adults", "Recovery from physical fatigue"],
    studies: [
      {
        title: "Acetyl-L-carnitine and diabetic neuropathy",
        authors: "Sima et al.",
        journal: "Diabetes Care",
        year: 2005,
        type: "RCT",
        sample: "1,257 patients with diabetic neuropathy",
        dose: "1,000–3,000 mg/day",
        duration: "52 weeks",
        finding: "ALCAR significantly improved nerve fiber regeneration, vibration perception, and pain scores in diabetic neuropathy vs placebo.",
        pubmedQuery: pm("acetyl L-carnitine diabetic neuropathy Sima Diabetes Care"),
      },
      {
        title: "ALCAR and mental fatigue: meta-analysis",
        authors: "Malaguarnera et al.",
        journal: "Pharmacological Research",
        year: 2018,
        type: "Meta-analysis",
        sample: "Multiple RCTs reviewed",
        dose: "1,500–3,000 mg/day",
        duration: "6–12 weeks",
        finding: "ALCAR significantly reduced physical and mental fatigue scores in older adults, post-illness recovery, and chronic fatigue syndromes.",
        pubmedQuery: pm("acetyl L-carnitine mental fatigue Malaguarnera"),
      },
      {
        title: "ALCAR in mild cognitive impairment and Alzheimer's",
        authors: "Montgomery et al.",
        journal: "International Clinical Psychopharmacology",
        year: 2003,
        type: "Meta-analysis",
        sample: "21 RCTs",
        dose: "1,500–3,000 mg/day",
        duration: "3+ months",
        finding: "ALCAR produced significant improvements in cognitive function scales in mild cognitive impairment and early Alzheimer's vs placebo.",
        pubmedQuery: pm("acetyl L-carnitine Alzheimer cognitive Montgomery"),
      },
    ],
  },

  // ─── Lighter coverage (3 studies each for popular ingredients) ──────────

  glycine: {
    ingredient: "glycine",
    evidenceLevel: "moderate",
    summary: "Glycine is a calming amino acid that lowers core body temperature and acts on NMDA receptors. Best-evidenced for improving sleep quality at 3 g doses before bed.",
    bestUseCases: ["Sleep depth and quality", "Faster sleep onset", "Recovery support for shift workers", "Mild glutamate modulation"],
    studies: [
      {
        title: "Glycine ingestion and subjective sleep quality",
        authors: "Yamadera et al.",
        journal: "Sleep and Biological Rhythms",
        year: 2007,
        type: "RCT",
        sample: "Adults with sleep complaints",
        dose: "3 g before bed",
        duration: "Acute and chronic",
        finding: "Glycine before bed significantly improved subjective sleep quality, reduced daytime sleepiness, and improved memory performance the following day.",
        pubmedQuery: pm("glycine sleep quality Yamadera"),
      },
      {
        title: "Glycine and core body temperature regulation",
        authors: "Bannai & Kawai",
        journal: "Neuropsychopharmacology Reports",
        year: 2012,
        type: "Mechanistic",
        sample: "Animal and small human studies",
        dose: "3 g",
        duration: "Acute",
        finding: "Glycine increases blood flow to extremities, lowering core body temperature — the mechanism behind its sleep-onset effect.",
        pubmedQuery: pm("glycine body temperature sleep Bannai"),
      },
    ],
  },

  "b-complex": {
    ingredient: "b-complex",
    evidenceLevel: "strong",
    summary: "B-vitamins are essential cofactors for energy, neurotransmitter synthesis, and methylation. Activated forms (methylfolate, methylcobalamin, P-5-P) bypass common genetic absorption issues.",
    bestUseCases: ["Stress with elevated cortisol", "Energy support", "MTHFR variants (methylated forms)", "Vegetarian/vegan supplementation", "Stress-induced cognitive fatigue"],
    studies: [
      {
        title: "B-vitamin complex and stress",
        authors: "Kennedy et al.",
        journal: "Human Psychopharmacology",
        year: 2010,
        type: "RCT",
        sample: "60 healthy adults",
        dose: "High-dose B-complex",
        duration: "33 days",
        finding: "B-complex significantly reduced stress, fatigue, and mental fatigue in healthy adults exposed to chronic occupational stress.",
        pubmedQuery: pm("B vitamin stress Kennedy human psychopharmacology"),
      },
      {
        title: "B-vitamins and homocysteine reduction",
        authors: "Clarke et al.",
        journal: "BMJ",
        year: 2002,
        type: "Meta-analysis",
        sample: "12 RCTs",
        dose: "Various",
        duration: "Variable",
        finding: "B6, B12, and folate supplementation produced consistent reductions in homocysteine, a cardiovascular risk marker.",
        pubmedQuery: pm("B vitamins homocysteine Clarke meta-analysis"),
      },
    ],
  },

  taurine: {
    ingredient: "taurine",
    evidenceLevel: "strong",
    summary: "Taurine is a conditionally essential amino acid concentrated in the heart, brain, and muscle. Recent landmark studies have implicated it in healthspan; older trials support cardiovascular and exercise outcomes.",
    bestUseCases: ["Cardiovascular function support", "Exercise endurance", "Bile acid synthesis (digestion)", "Possibly longevity (emerging)"],
    studies: [
      {
        title: "Taurine deficiency as a driver of aging",
        authors: "Singh et al.",
        journal: "Science",
        year: 2023,
        type: "Mechanistic",
        sample: "Animals + 12,000 human serum samples",
        dose: "Varied",
        duration: "Lifelong",
        finding: "Blood taurine levels decline with age across species; restoring taurine in middle-aged animals extended healthy lifespan. Strong correlations in humans.",
        pubmedQuery: pm("taurine aging Singh Science 2023"),
      },
      {
        title: "Taurine and exercise capacity in heart failure",
        authors: "Beyranvand et al.",
        journal: "Journal of Cardiology",
        year: 2011,
        type: "RCT",
        sample: "29 heart failure patients",
        dose: "1.5 g/day",
        duration: "2 weeks",
        finding: "Taurine significantly improved exercise capacity, peak oxygen uptake, and walking distance in heart failure patients vs placebo.",
        pubmedQuery: pm("taurine heart failure exercise Beyranvand"),
      },
    ],
  },

  "alpha-gpc": {
    ingredient: "alpha-gpc",
    evidenceLevel: "strong",
    summary: "Alpha-GPC is the most bioavailable choline source for the brain. Established for cognitive support in mild dementia; growing evidence for athletic performance.",
    bestUseCases: ["Mild cognitive impairment (clinical use)", "Acute focus and reaction time", "Power output before training", "Recovery from stroke (clinical)"],
    studies: [
      {
        title: "Alpha-GPC and mild-to-moderate Alzheimer's",
        authors: "De Jesus Moreno",
        journal: "Clinical Therapeutics",
        year: 2003,
        type: "RCT",
        sample: "261 mild-moderate Alzheimer's patients",
        dose: "1,200 mg/day",
        duration: "180 days",
        finding: "Alpha-GPC produced significant improvements in cognitive function tests vs placebo and was well-tolerated over 6 months.",
        pubmedQuery: pm("alpha GPC Alzheimer Clinical Therapeutics"),
      },
      {
        title: "Alpha-GPC and exercise performance",
        authors: "Bellar et al.",
        journal: "Journal of the International Society of Sports Nutrition",
        year: 2015,
        type: "RCT",
        sample: "13 healthy adults",
        dose: "600 mg pre-exercise",
        duration: "Single dose",
        finding: "Alpha-GPC significantly increased lower-body power output and peak bench press force vs placebo in resistance-trained individuals.",
        pubmedQuery: pm("alpha GPC exercise performance Bellar"),
      },
    ],
  },

  citicoline: {
    ingredient: "citicoline",
    evidenceLevel: "strong",
    summary: "Citicoline (CDP-Choline) — Cognizin is the patented form — supports both choline-based acetylcholine synthesis and phosphatidylcholine membrane integrity. Evidence-leading for attention.",
    bestUseCases: ["Adolescent attention and processing speed", "Adult attention performance", "Stroke recovery (clinical)", "Age-related memory complaints"],
    studies: [
      {
        title: "Citicoline and attention in healthy adolescents",
        authors: "McGlade et al.",
        journal: "Food and Nutrition Sciences",
        year: 2012,
        type: "RCT",
        sample: "75 healthy adolescent males",
        dose: "250–500 mg/day Cognizin",
        duration: "28 days",
        finding: "Citicoline significantly improved attention performance and reduced impulsivity vs placebo on continuous performance tasks.",
        pubmedQuery: pm("citicoline attention adolescents McGlade"),
      },
      {
        title: "Citicoline in older adults with age-related memory complaints",
        authors: "Spiers et al.",
        journal: "Archives of Neurology",
        year: 1996,
        type: "RCT",
        sample: "95 older adults",
        dose: "1,000 mg/day",
        duration: "3 months",
        finding: "Citicoline improved word-list recall and other verbal memory measures in adults with age-associated memory impairment.",
        pubmedQuery: pm("citicoline memory older adults Spiers"),
      },
    ],
  },
};

// ─── Helpers ──────────────────────────────────────────────────────────────

export function getResearch(slug: string): ResearchEntry | undefined {
  return RESEARCH[slug];
}

export function getStudyCount(slug: string): number {
  return RESEARCH[slug]?.studies.length ?? 0;
}

export function buildPubmedSearchUrl(query: string): string {
  return `https://pubmed.ncbi.nlm.nih.gov/?term=${query}`;
}

export function buildStudyLink(study: Study): string {
  if (study.pmid) return `https://pubmed.ncbi.nlm.nih.gov/${study.pmid}/`;
  return buildPubmedSearchUrl(study.pubmedQuery);
}

/**
 * Fallback for ingredients without a curated entry — points to a useful
 * PubMed search built from the supplement's name and key tags.
 */
export function fallbackResearchUrl(supplementName: string, tags: string[] = []): string {
  const q = [supplementName, ...tags.slice(0, 3)].join(" ");
  return buildPubmedSearchUrl(pm(q));
}
